didx-xyz/acapy-cloud

- app/routers/.gitattributes
This should close [PR
10](https://github.com/didx-xyz/aries-cloudapi-python/pull/10) and fix
line endings for windows machines
closes #10
> Add git attributes to fix line-ending

- app/acapy_ledger_facade.py
- app/acapy_wallet_facade.py
- app/core/wallet.py
- app/tests/conftest.py
- app/tests/test_acapy_ledger_facade.py
- app/tests/test_acapy_wallet_facade.py
- docker-compose.yaml
- environments/yoma-ga/aca-py-agent.default.env
- environments/yoma-ga/fastapi.default.env
- manage
* Is disabled in the setup for now. See tails server annotation in
* docker-compose
* agent env files and
* manage script
> Add tails server setup to enable possibility of revocation

- CONTRIBUTING.md
- SECURITY.md
Contribution: contains detailed description for making contributions to Yoma
Security: contains description for submitting reports about security bugs
>  Adding Contribution guidelines and Security policy

- LICENSE
Adding date + copyright owner name
> Copyright Update

- app/tests/conftest.py
- app/tests/test_issuer_v1.py
@morrieinmaas creating a pull request to facilitate the review and merging of my adjustments to your tests
> Adjusted tests to work with module fixtures

- app/dependencies.py
- app/generic/wallet/wallets.py
- app/routers/schema.py
- app/tests/conftest.py
- app/tests/test_connections.py
- app/tests/test_dependencies.py
- junit.xml
the wallet_id variable si not required for the controller, hence I
removed it.
closes #109
> Remove redundant wallet_id

- .github/workflows/continuous-build.yml
NOTE: I currently dont have maintainer rights in the repo so I cannot
set up the secrets required for this to run successfully
> Add deploy to EC2 on merge or push into development

- .github/workflows/continuous-build.yml
Signed-off-by: Timo Glastra <timo@animo.id>
> ci: fix if statement for deploy

- .github/workflows/continuous-build.yml
According to StackOverflow this mitigates the urlib3 chardet version issue.
closes #153
> [WIP] Install docker-compose without getting version conflicts in urllib3 and chardot

- app/dependencies.py
- app/facades/trust_registry.py
- app/tests/test_dependencies.py
- docker-compose.yaml
* Specifying str type for role and
* checking either auth token/key is there
> Fix hanging swagger by:

- app/facades/ledger.py
- app/facades/trust_registry.py
- app/requirements.txt
- app/tests/facades/test_trust_registry.py
- app/tests/test_via_web_wallet.py
- requirements.dev.txt
replace requests calls by httpx calls and remove requests from the requirements.
> feat: use httpx as single http request library

- app/generic/verifier/facades/acapy_verifier_utils.py
- app/generic/verifier/models.py
- app/tests/e2e/test_verifier.py
- app/tests/verifier/test_verifier_utils.py
Add presentation_request to PresentationExchange
closes #183
> Homogenise presentation format to indy (Dict) in PresentationExchange

- Makefile
- README.md
> Add running unit tests only and add to README

- app/requirements.txt
> fix: update pyjwt version flagged by dependabot

- app/admin/tenants/onboarding.py
- app/tests/admin/test_onboarding.py
- app/tests/e2e/test_tenants.py
- docs/Governance as Code.md
- requirements.dev.txt
- trustregistry/tests/test_actor.py
> feat: issuer onboarding with multiuse invite on trust registry

- app/generic/connections/connections.py
- app/generic/verifier/models.py
- app/generic/verifier/verifier.py
- app/tests/e2e/test_verifier.py
- app/tests/verifier/test_verifier.py
- shared_models/shared_models.py
* create invite works
* accept invite works
* both OOB
* BUT: no proof request is going through
> feat: enable connectionless proof

- shared_models/shared_models.py
> fix: add missing state abandoned to credential exchange

- app/admin/tenants/tenants.py
- app/tests/e2e/test_tenants.py
- app/tests/e2e/test_verifier.py
- endorser/tests/test_endorser_processor.py
> fix: correctly return group id from for tenants

- app/admin/tenants/onboarding.py
- app/tests/admin/test_onboarding.py
- app/tests/e2e/test_tenants.py
- app/tests/e2e/test_verifier.py
> feat: add multiuse invite to issuer trust registry

- .github/workflows/codeql-analysis.yml
- .github/workflows/continuous-build.yml
The purpose of the current deploy job is unclear, and is currently failing. Resolution is to remove it for the meantime.
Made the duplicate PR to test out the failing CodeQL analysis
> Remove deploy job from `continuous-build.yml` and update CodeQL workflow

- app/generic/verifier/verifier.py
```py
- @router.get("/proofs/{proof_id}")
+ @router.get("/proofs/{proof_id}", response_model=PresentationExchange)
```
etc
> :art: add missing verifier response models

- webhooks/dependencies/sse_manager.py
Previously, incoming webhook events were directly queued to the per-wallet event queues. 
There is concurrency management in the SSE Manager which may slow down the processing of new events. This may cause timeouts on the cloudagent side, which is submitting the webhook events and expecting timely confirmations.
Now the queueing of incoming events is decoupled from adding events to the per wallet queues.
> SSE: Decouple queueing of incoming events from queueing of per-wallet events

- app/tests/test_did.py
- app/util/did.py
> ed25519 verkey validation in did conversion

- trustregistry/tests/test_actor.py
added tests for get actors by id, name, did
> Test get actor

- app/dependencies/auth.py
- app/models/tenants.py
- app/routes/admin/tenants.py
- app/routes/issuer.py
- app/tests/e2e/test_credentials.py
- app/tests/e2e/test_issuer.py
- app/tests/e2e/test_jsonld.py
- app/tests/e2e/test_messaging.py
- app/tests/e2e/test_oob.py
- app/tests/e2e/test_tenants.py
- app/tests/e2e/test_trust_registry_integration.py
- app/tests/e2e/test_verifier.py
- app/tests/util/ecosystem_connections.py
- app/tests/util/tenants.py
- app/tests/util/trust_registry.py
- endorser/endorser_processor.py
Additional refactoring:
- moved model + util definitions out of route definition for admin: tenants
- fixed various codeql suggestions
- Parameterized route prefixes in tests
> :art: Refactoring continued

- .github/dependabot.yml
- .github/workflows/codacy.yml
- .github/workflows/continuous-build.yml
- .github/workflows/continuous-deploy.yml
- .github/workflows/sonarcloud.yml
- .github/workflows/style-check.yml
* Add github actions to dependabot
* Bump github action versions
> Update Github Actions

- app/tests/util/client.py
- shared/constants.py
- webhooks/dependencies/sse_manager.py
- webhooks/routers/sse.py
Configure SSE timeouts/periods.
> sse constants

- app/tests/e2e/issuer/did_key_bbs/test_ld_bbs.py
- app/tests/e2e/issuer/did_key_ed/test_ld_ed25519.py
- Waiting for correct state before getting `exchange_record`
- Fixed OOB test for json_ld tests 
Closes #478
> Fix Json_LD tests

- .github/workflows/continuous-deploy.yml
Combine coverage reports from matrix steps and upload to Codacy.
> Fix coverage report

- .github/workflows/continuous-deploy.yml
- app/routes/definitions.py
Temporarily ignore failing tests.
> Temporary sleep workaround

- .github/workflows/continuous-deploy.yml
- docker-compose.yaml
- dockerfiles/agents/Dockerfile
- dockerfiles/agents/Dockerfile.agent
- dockerfiles/agents/Dockerfile.author.agent
- dockerfiles/endorser/Dockerfile
- dockerfiles/fastapi/Dockerfile
- dockerfiles/tests/Dockerfile
- dockerfiles/trustregistry/Dockerfile
- dockerfiles/webhooks/Dockerfile
- trustregistry/requirements.txt
- webhooks/requirements.txt
* Don't use official FastAPI docker image
* According to FastAPI Documentation, you shouldn't use the official
FastAPI docker image in k8s
* Also add `--no-cache-dir` to `pip install` commands to reduce docker
image size
* Use `slim` docker images
> Optimize Dockers

- shared/models/topics/__init__.py
- shared/models/topics/base.py
- webhooks/dependencies/service.py
- Added `problem_report` model.
- Added transformer to webhook service.
- Added `problem_report` topic mapping
Closes #446
> Map `problem_report` webhook event

- dockerfiles/agents/Dockerfile.agent
- dockerfiles/agents/Dockerfile.author.agent
Following up from update to wallet-plugin: https://github.com/didx-xyz/acapy-wallet-groups-plugin/pull/14
> :arrow_up: upgrade wallet-plugin

- .github/workflows/continuous-deploy.yml
- app/tests/issuer/test_issuer.py
Check if any test failed and the fail `Status Check` job. Can be used as a single status check to verify that tests have passed.
> Status check hotfix

- app/dependencies/auth.py
- app/dependencies/role.py
- app/routes/admin/tenants.py
Only tenant-admin's can call methods on tenant route
> Update tenant-admin auth

- trustregistry/database.py
Allows env variable config for pool_size and max_overflow in trust registry postgres engine
> :sparkles: add env config for trust registry postgres engine

- app/tests/e2e/test_tenants.py
> :white_check_mark: cleanup tenant after creation in test

- shared/log_config.py
for DataDog
New env vars: 
- `ENABLE_FILE_LOGGING`
- `DISABLE_COLORIZE_LOGS`
By default, file logging is off, and colorized logs is on.
To disable colorize logs: `DISABLE_COLORIZE_LOGS=true`
> :sparkles: add env config to disable file logging or colorizing

- app/models/issuer.py
- app/routes/definitions.py
- app/routes/issuer.py
- app/routes/jsonld.py
- app/routes/wallet/credentials.py
- app/routes/wallet/dids.py
- app/services/revocation_registry.py
- app/tests/e2e/conftest.py
- app/tests/e2e/test_credentials.py
- app/tests/e2e/test_revocation.py
- app/tests/services/test_revocation_registry.py
Removed bad code from create cred_def
Exposed new routes:
- publish pending revocations
- clear pending revocations
- get credential revocation status
closes #488
> Fix revocation

- app/routes/websocket_endpoint.py
> add v1 to websocket routes

- webhooks/dependencies/sse_manager.py
Problem: `_listen_for_new_events` is a background task in SseManager that listens for new redis events on a pubsub channel. If a redis connection error is raised, this listener will silently exit, losing SSE functionality.
Hotfix: Handle `aioredis.ConnectionError` and retry redis pubsub connections before raising sigterm if consecutive connection errors occur
To-do later:
- refine redis config (for timeout, retries, etc)
- add health check to webhooks service
> :ambulance: Hotfix: handle redis pubsub connection error

- .github/workflows/continuous-deploy.yml
Shared storage for local `tails` file on mt-agent `/home/aries/.indy_client`
> Shared local tails storage

- app/main.py
- app/models/jws.py
- app/models/sd_jws.py
- app/routes/wallet/jws.py
- app/routes/wallet/sd_jws.py
- app/tests/e2e/test_wallet_jws.py
- app/tests/e2e/test_wallet_sd_jws.py
New endpoints:
- /wallet/jws/sign
- /wallet/jws/verify
- /wallet/sd-jws/sign
- /wallet/sd-jws/verify
> :sparkles: Implement JWS and SD-JWS sign and verify routes

- app/routes/issuer.py
- app/routes/jsonld.py
- app/routes/wallet/jws.py
- app/routes/wallet/sd_jws.py
- app/services/issuer/acapy_issuer_v1.py
- app/services/issuer/acapy_issuer_v2.py
Removes credential payloads from being included in logging
> :mute: Do not log credential attributes

- app/routes/definitions.py
The `create_credential_definition` method finishes by calling `get_credential_definition` ... this is because the ACA-Py result does not contain the extra data we want to include in our response, so we call `get` to have consistent responses.
The problem is, that calling `get` on a freshly created cred def can lead to race conditions, where the records are not yet complete in ACA-Py, and so `get` raises a 404.
This PR adds retry logic to avoid such scenarios.
___
Example of where this race condition popped up:
https://github.com/didx-xyz/aries-cloudapi-python/actions/runs/8601203055/job/23567949971?pr=745
> :bug: Fix race condition when creating credential definitions

- .github/dependabot.yml
- .github/workflows/codacy.yml
- .github/workflows/sonarcloud.yml
Pull request is to test a change in charts, but may as well include some format changes and dependabot schedule update
> :construction_worker: Update dependabot schedule

- openapi/tenant-admin-openapi.json
- openapi/tenant-admin-openapi.yaml
- openapi/tenant-openapi.json
- openapi/tenant-openapi.yaml
This PR adds the json and yaml docs for the tenant and tenant-admin openapi specs. This will assists in tracking changes to our swagger docs in future upgrades
> :memo: Add openapi specs to project

- trustregistry/tests/test_list_type.py
Added test for:
`trustregistry/list_type.py`
> Added test for `StringList`  type decorator

- trustregistry/tests/test_main.py
> Add tests for `trustregistry/main.py`

- trustregistry/tests/test_db.py
- trustregistry/tests/test_registry_actors.py
The `trustregistry` should be 100% covered now.
> Added tests for `trustregistry/db.py`

- openapi/tenant-openapi.json
- openapi/tenant-openapi.yaml
No breaking changes. Just RejectProofRequest now has an flag to optionally delete proof exchange records with a reject request.
> :memo: Update openapi spec

- app/tests/e2e/conftest.py
- app/tests/e2e/verifier/test_proof_revoked_credential.py
- app/tests/fixtures/credentials.py
Added fixture to add revoked credential.
Test that credential to check still revoked
> Regression test revoked credential

- app/models/connections.py
- app/routes/connections.py
- app/tests/e2e/test_connections.py
> Update Connections doc strings

- app/tests/e2e/conftest.py
- app/tests/e2e/verifier/test_verifier.py
- app/tests/fixtures/credentials.py
- app/tests/util/regression_testing.py
- Add new fixture get or issue valid credential
- do proof request against valid credential
> Regression test valid credential

- app/services/acapy_ledger.py
- app/services/revocation_registry.py
- app/services/verifier/acapy_verifier_v1.py
- app/services/verifier/acapy_verifier_v2.py
- app/tests/e2e/verifier/test_predicate_proofs.py
- app/tests/services/test_revocation_registry.py
- app/tests/services/verifier/test_acapy_verifier_v1.py
- app/tests/services/verifier/test_acapy_verifier_v2.py
Added e2e tests for predicate indy proofs
> Predicate proof tests

- app/requirements.txt
- docker-compose.yaml
- dockerfiles/agents/Dockerfile.agent
- dockerfiles/agents/Dockerfile.author.agent
- endorser/requirements.txt
- webhooks/requirements.txt
Upgrades to the latest ACA-Py nightly build, specifically to add support for wallet_list pagination
> :arrow_up: upgrade to latest ACA-Py build

- .github/workflows/continuous-deploy.yml
* Tailscale `1.62.1` -> `1.68.1`
* Helmfile `v0.163.1` -> `v0.166.0`
* Helm `v3.14.3` -> `v3.15.2`
> Update Helm, Helmfile, and Tailscale

- app/requirements.txt
- docker-compose.yaml
- dockerfiles/agents/Dockerfile
- dockerfiles/agents/Dockerfile.agent
- dockerfiles/agents/Dockerfile.author.agent
- endorser/requirements.txt
- openapi/tenant-openapi.json
- openapi/tenant-openapi.yaml
- webhooks/requirements.txt
Updates base ACA-Py image from nightly build to 1.0.0rc4, together with dependencies:
- [Aries cloud-controller](https://github.com/didx-xyz/aries-cloudcontroller-python/releases/tag/v1.0.0rc4)
- [wallet group-id plugin](https://github.com/didx-xyz/acapy-wallet-groups-plugin/releases/tag/1.0.0rc4)
- [redis events plugin](https://github.com/didx-xyz/aries-acapy-plugins/releases/tag/v1-2024-07-11)
> :arrow_up: ACA-Py 1.0.0rc4

- app/routes/issuer.py
- app/tests/e2e/issuer/ld_proof/test_ld_proof_did_key_bbs.py
- app/tests/e2e/issuer/ld_proof/test_ld_proof_did_key_ed25519.py
- app/tests/e2e/issuer/ld_proof/test_ld_proof_did_sov.py
- app/tests/e2e/issuer/test_indy_credentials.py
- app/tests/e2e/issuer/test_save_exchange_record.py
- app/tests/e2e/verifier/test_proof_revoked_credential.py
Increases sleep durations to accommodate increased lag with more tenants/records
> :white_check_mark: adjust sleep durations in tests

- app/services/issuer/acapy_issuer.py
- app/tests/e2e/test_tenants.py
- dockerfiles/agents/Dockerfile
- scripts/k6/README.md
- webhooks/tests/e2e/test_sse.py
Resolves some of the code scanning alerts
> :art: fix lint warnings

- app/tests/e2e/verifier/test_self_attested.py
Add e2e test for `self_attested_attributes`
> ✅ Add `self_attested_attributes` e2e test

- scripts/k6/libs/functions.js
- scripts/k6/scenarios/create-creddef.js
- scripts/k6/scenarios/create-issuers.js
- scripts/k6/scenarios/delete-issuers.js
- scripts/k6/scripts/governance-ha.sh
Phased scenarios to create issuers and credential definitions + rudimentary bash wrapper to script ha-config validation.
> ✅ K6 cred def

- .github/workflows/continuous-deploy.yml
- app/poetry.lock
- app/pyproject.toml
Run pytests concurrently with `pytest-xdist`.
> ⚡✅ Add pytest-xdist to pytest container

- scripts/k6/libs/setup.js
- scripts/k6/run_tests.sh
- scripts/k6/scenarios/bootstrap-issuer.js
- scripts/k6/scenarios/create-credentials.js
- scripts/k6/scenarios/create-holders.js
- scripts/k6/scenarios/create-invitations.js
- scripts/k6/scenarios/create-proof.js
- scripts/k6/scenarios/revoke-credentials.js
- scripts/k6/scripts/collection_credential.sh
- scripts/k6/scripts/collection_holder.sh
- scripts/k6/scripts/collection_invitation.sh
- scripts/k6/scripts/collection_proof.sh
- scripts/k6/scripts/collection_revocation.sh
- scripts/k6/scripts/collection_schema.sh
- scripts/k6/scripts/common.sh
- scripts/k6/scripts/main.sh
Missing collections and some refactoring to remove setup function duplication.
> ✅ K6 collections

- app/poetry.lock
- endorser/poetry.lock
- trustregistry/poetry.lock
- webhooks/poetry.lock
And dev dependencies: mockito, pylint
> :arrow_up: Upgrade fastapi, sqlalchemy, starlette

- .github/workflows/continuous-deploy.yml
* Flush Redis Async
* Reset NATS when reset deployments
---
Todo:
> :construction_worker: Add Reset NATS Step

- shared/log_config.py
`deepcopy` broke Datadog APM...
> remove deepcopy

- tilt/cloudapi/Tiltfile
- tilt/cloudapi/nats/templates/job.yaml
- tilt/cloudapi/nats/values.yaml
* Bump Redis Insight Helm `1.0.1` -> `1.1.0`
* Set NATS KV and Stream Replicas to match NATS ReplicaCount
> 🧑‍💻 Set NATS KV and Stream Replicas

- resources/postman-prf.md
- scripts/k6/libs/functions.js
- scripts/k6/libs/setup.js
- scripts/k6/scenarios/bootstrap-issuer.js
- scripts/k6/scenarios/create-credentials.js
- scripts/k6/scenarios/create-invitations.js
- scripts/k6/scenarios/create-proof.js
- scripts/k6/scenarios/revoke-credentials.js
- scripts/k6/scripts/collection_credential.sh
- scripts/k6/scripts/collection_holder.sh
- scripts/k6/scripts/collection_invitation.sh
- scripts/k6/scripts/collection_issuer.sh
- scripts/k6/scripts/collection_proof.sh
- scripts/k6/scripts/collection_revocation.sh
- scripts/k6/scripts/config.sh
- multi-issuer multi-holder
- SSE refactor
> ♻️✨ K6: Waypoint ha validation

- .github/workflows/continuous-deploy.yml
- scripts/redis-expire.sh
Temporary solution until we remove Redis. Currently Waypoint slows down significantly after a single pytest run.
Update:
- detect master node
- batch requests
- enable debug
> Expire Redis keys after each pytest

- .github/workflows/continuous-deploy.yml
- scripts/redis-expire.sh
Temporary workaround:
- NATS also has to be reset after Redis keys have been expired
> 👷 Reset NATS after each pytest

- .mise/tasks/kind/kind.yaml
- dockerfiles/endorser/Dockerfile
- dockerfiles/fastapi/Dockerfile
- dockerfiles/trustregistry/Dockerfile
- dockerfiles/waypoint/Dockerfile
* Copy `pyproject.toml` and `poetry.lock` files
* Then do `poetry install`
* Then copy everything else
* Prevents invalidating all the cache whenever code changes
> :zap: 🧑‍💻 More efficient docker cache usage

- scripts/k6/libs/functions.js
- scripts/k6/scenarios/create-credentials.js
- scripts/k6/scenarios/create-holders.js
- scripts/k6/scenarios/create-invitations.js
- scripts/k6/scenarios/create-proof.js
- scripts/k6/scenarios/revoke-credentials.js
- scripts/k6/scripts/collection_credential.sh
- scripts/k6/scripts/collection_holderops.sh
- scripts/k6/scripts/collection_issuerops.sh
- scripts/k6/scripts/common.sh
- scripts/k6/scripts/config.sh
Collections to run all holder & issuer related operations (K6 scenarios) while restarting k8s deployments during each scenario.
> ✅ K6 fault tolerance

- .github/workflows/continuous-deploy.yml
* Instead of repo managed secret for cloning Charts, use Org secret
> :construction_worker: Use Github Org `CHARTS_PAT` secret

- .github/workflows/continuous-deploy.yml
* Seeing as Redis is no longer used we don't need to clean it anymore
> :construction_worker: Remove Redis from CICD

- app/poetry.lock
- app/pyproject.toml
- endorser/poetry.lock
- endorser/pyproject.toml
- trustregistry/poetry.lock
- waypoint/poetry.lock
Includes cloudcontroller upgrades:
- https://github.com/didx-xyz/aries-cloudcontroller-python/pull/212
- https://github.com/didx-xyz/aries-cloudcontroller-python/pull/214
> :arrow_up: Upgrade cloudcontroller

- .github/workflows/validate-pr.yml
* Add a Markdown Comment to identify comments left by PR validator
> 👷 Filter PR Validator Comments

- app/routes/sse.py
- app/services/event_handling/sse.py
- shared/constants.py
- waypoint/routers/sse.py
- waypoint/services/nats_service.py
> 🔧 Configure SSE `look_back` default as env var

- docker-compose-ledger.yaml
- tilt/cloudapi/Tiltfile
* Drop `governance-` prefix
* Add `d-pay/` prefix
> 👷 Rename Local

- .github/workflows/codacy.yml
- .github/workflows/continuous-deploy.yml
- .github/workflows/sonarcloud.yml
- .github/workflows/style-check.yml
- docker-compose-ledger.yaml
- tilt/cloudapi/Tiltfile
Rename all images (dropping `governance` prefix) and prepending with `d-cloud/`
> 👷 Rename GHCR images

- .github/workflows/continuous-deploy.yml
- tilt/cloudapi/nats/templates/job.yaml
- tilt/cloudapi/nats/values.yaml
Remove NATS kv from local and dev
> :fire: Remove NATS kv

- .github/workflows/continuous-deploy.yml
- .mise.toml
- README.md
* There's a small "bug" in Mise (jdx/mise#3071)
* This is a workaround for the "bug"
> :bug: 🧑‍💻 Fix Mise Tasks

- app/models/tenants.py
- app/routes/admin/tenants.py
- app/tests/e2e/test_auth.py
- app/tests/e2e/test_tenants.py
- app/tests/routes/admin_tenants/test_get_wallet_auth_token.py
- scripts/k6/main.js
- scripts/k6/scenarios/delete-holders.js
- scripts/k6/scenarios/delete-issuers.js
Update docstrings
Deprecated  `GET .../v1/tenants/{wallet_id}/access-token`
Added `POST .../v1/tenants/{wallet_id}/access-token`
Breaking changes:
- Delete tenant endpoint from `200` to `204` status code
> 📝 💥Swagger tenant admin

- openapi/tenant-admin-openapi.json
- openapi/tenant-admin-openapi.yaml
- openapi/tenant-openapi.json
- openapi/tenant-openapi.yaml
As of 4.1.0-1, to assist with tracking changes
> :memo: Update openapi specs

- app/main.py
- app/routes/revocation.py
- app/tests/e2e/test_revocation.py
- app/tests/routes/revocation/test_fix_revocation_registry.py
- app/tests/services/issuer/test_issuer.py
Add fix-rev-reg endpoint: `/v1/issuer/credentials/fix-revocation-registry/{revocation_registry_id}`
> ✨ Add endpoint to fix revocation registry state

- docs/examples/4. Create Connection with Issuer.md
- docs/examples/6. Create Connection with Verifier.md
- docs/examples/7. Verify Credential.md
Update connection example to use did-exchange and oob
> 📝Update connection examples

- .gitignore
- README.md
- helm/acapy-test/.helmignore
- helm/acapy-test/Chart.lock
- helm/acapy-test/Chart.yaml
- helm/acapy-test/conf/.gitignore
- helm/acapy-test/conf/local/regression.yaml
- helm/acapy-test/conf/local/values.yaml
- helm/acapy-test/templates/_helpers.tpl
- helm/acapy-test/templates/job.yaml
- helm/acapy-test/templates/pvc.yaml
- helm/acapy-test/templates/secret.yaml
- helm/acapy-test/templates/serviceaccount.yaml
- helm/acapy-test/values.yaml
* Add the required Helm assets to run containerized tests in local dev
Closes DIDC-307
> :technologist: Add Helm assets to run containerized tests

- .github/workflows/README.md
* Use mermaid to draw simple cicd flowchart
* Remove outdated information about very old and deprecated helm charts
> :memo: Update CICD `README.md`

- helm/acapy-cloud.yaml.gotmpl
- tilt/acapy-cloud/Tiltfile
- tilt/metrics/Tiltfile
* Metrics Server `7.3.4` -> `7.4.0`
* PostgreSQL HA `15.1.7` -> `15.3.0`
* PGAdmin `1.34.0` -> `1.35.0`
> :arrow_up: Upgrade Local/Dev Infra

- .github/workflows/validate-pr.yml
* Add global to emoji regex
* Trim trailing spaces in PR title
* Add some debug output
> :construction_worker: Fix PR Length Check

- .github/workflows/cicd.yml
- helm/acapy-cloud/values.yaml
* Bump Mise `2025.2.8` -> `2025.3.0`
* Bump DDTrace `3.0.0` -> `3.1.0`
* Unpin Tailscale
> :arrow_up: :construction_worker: Bump Mise, DDTrace, and unpin Tailscale

- .github/workflows/validate-pr.yml
* Add escaped backticks for example emojis in PR comment
* Makes it easier to see examples
> 👷 Add escaped backticks for example emojis

- helm/nats/Chart.lock
* `bitnami/nats` `9.0.1` -> `9.0.4`
* `bitnami/common` `2.29.1` -> `2.30.0`
> :arrow_up: 🧑‍💻 Update NATS Chart.lock

- helm/acapy-cloud/conf/dev/governance-agent.yaml
- helm/acapy-cloud/conf/dev/mediator.yaml
- helm/acapy-cloud/conf/dev/multitenant-agent.yaml
- helm/acapy-cloud/conf/dev/waypoint.yaml
- helm/acapy-cloud/conf/local/governance-agent.yaml
- helm/acapy-cloud/conf/local/mediator.yaml
- helm/acapy-cloud/conf/local/multitenant-agent.yaml
- helm/acapy-cloud/conf/local/waypoint.yaml
* Add Startup Probes
* Remove initial delay from health probes
* Faster startup times
> :technologist: Faster health probes and startup probes

- app/poetry.lock
- endorser/poetry.lock
- trustregistry/poetry.lock
- trustregistry/pyproject.toml
- waypoint/poetry.lock
alembic from 1.14.1 to 1.15.1
fastapi from 0.115.10 to 0.115.11
pytest from 8.3.4 to 8.3.5
> :arrow_up: Update alembic, fastapi, pytest

- app/routes/oob.py
- app/tests/routes/oob/test_accept_oob_invitation.py
- app/tests/routes/oob/test_connect_public_did.py
- app/tests/routes/oob/test_create_oob_invitation.py
> ✅ Oob unit tests

- app/routes/admin/tenants.py
- app/routes/issuer.py
- app/routes/revocation.py
- app/routes/verifier.py
Updated docstrings where needed for `wallet_type` and `anoncreds`.
> 📝 Update docstrings re: anoncreds wallet types

- app/services/definitions/schemas.py
- endorser/tests/test_util_endorsement.py
- endorser/util/endorsement.py
- endorser/util/transaction_record.py
- shared/models/endorsement.py
Adds Schema transaction types to Endorser's applicable endorsement list
> :sparkles: Endorse Schema transactions

- app/tests/e2e/test_definitions.py
- app/tests/fixtures/member_wallets.py
> :white_check_mark: e2e test for fetching AnonCreds schema

- app/tests/e2e/test_definitions.py
Removes skipping of anoncreds schema e2e tests in regression mode
> :white_check_mark: AnonCreds schema regression tests

- app/tests/e2e/test_definitions.py
- dockerfiles/agents/Dockerfile
🚧 Testing a fix for https://github.com/openwallet-foundation/acapy/issues/3600 ✅ Seems all good
> :test_tube: e2e test for creating AnonCreds cred def

- .github/workflows/cicd.yml
- .mise.toml
- .mise/tasks/kind/install/docker-cache
- helm/acapy-cloud.yaml.gotmpl
- helm/nats/Chart.lock
- tilt/acapy-cloud/Tiltfile
- tilt/metrics/Tiltfile
* Mise `2025.3.0` -> `2025.3.7`
* NATS CLI `0.1` -> `0.2`
* Istio `1.24` -> `1.25`
* Tilt `0.33` -> `0.34`
* Add `--dns` options to Docker Cache
* Prevents DNS issues in Docker Cache
* NATS `9.0.4` -> `9.0.7`
* Metrcs Server `7.4.0` -> `7.4.1`
* Postgres `15.3.3` -> `15.3.8`
* PGAdmin `1.35.0` -> `1.36.0`
> 🧑‍💻 ⬆️ Upgrade Mise and local infra

- .vscode/settings.json
- app/poetry.lock
- app/pyproject.toml
- app/tests/e2e/issuer/ld_proof/test_ld_proof_did_key_bbs.py
- app/tests/e2e/issuer/ld_proof/test_ld_proof_did_key_ed25519.py
- app/tests/e2e/issuer/ld_proof/test_ld_proof_did_sov.py
- app/tests/e2e/issuer/test_anoncreds_credentials.py
- app/tests/e2e/issuer/test_connections_use_public_did.py
- app/tests/e2e/issuer/test_indy_credentials.py
- app/tests/e2e/test_connections.py
- app/tests/e2e/test_definitions.py
- app/tests/e2e/test_did_exchange.py
- app/tests/e2e/test_did_rotate.py
- app/tests/e2e/test_jsonld.py
- app/tests/e2e/test_messaging.py
- app/tests/e2e/test_oob.py
- app/tests/e2e/test_tenants.py
- app/tests/e2e/test_trust_registry.py
- app/tests/e2e/test_wallet_dids.py
- app/tests/services/issuer/test_acapy_issuer_v2.py
- app/tests/services/onboarding/test_onboarding.py
- app/tests/services/test_acapy_ledger.py
- app/tests/services/verifier/test_verifier_utils.py
- app/tests/test_util_definitions.py
- waypoint/poetry.lock
- waypoint/pyproject.toml
The dependency is no longer compatible with poetry
> :heavy_minus_sign: Remove and replace `assertpy`

- .mise/tasks/kind/install/docker-cache
* New release
* All dependencies updated
---
https://github.com/rpardini/docker-registry-proxy/releases/tag/0.6.5
> :arrow_up: :technologist: Update Docker Proxy

- dockerfiles/agents/Dockerfile
Pulls in an acapy release with the fix for https://github.com/openwallet-foundation/acapy/issues/3607
> :bug: Fix ledger DID endpoint rewrites

- app/pyproject.toml
- app/routes/admin/tenants.py
- docs/openapi/tenant-admin-openapi.json
- docs/openapi/tenant-admin-openapi.yaml
- docs/openapi/tenant-openapi.json
- docs/openapi/tenant-openapi.yaml
- endorser/pyproject.toml
- shared/constants.py
- trustregistry/pyproject.toml
- waypoint/pyproject.toml
> :bookmark: 5.0.0rc0

- helm/acapy-cloud/conf/postgres.yaml
* Tune PGPool connections to improve stability under load
* Should reduce cases of tests causing PGPool to refuse connections
> :technologist: Attempt to improve stability of PGPool

- .github/workflows/cicd.yml
- docker-compose.yaml
- tilt/acapy-cloud/Tiltfile
From 1.8.0 to 1.9.0
https://github.com/bcgov/von-network/releases/tag/v1.9.0
> :arrow_up: Upgrade von-network

- app/tests/e2e/verifier/anoncreds/test_verifier.py
Credential must contain attr with certain value
> ✅ Restriction on proof

- app/tests/e2e/README.md
- app/tests/e2e/docs/connections.md
- app/tests/e2e/docs/issuer.md
- app/tests/e2e/docs/miscellaneous.md
- app/tests/e2e/docs/oob_message_json_ld.md
- app/tests/e2e/docs/regression.md
- app/tests/e2e/docs/revocation.md
- app/tests/e2e/docs/schema_definitions.md
- app/tests/e2e/docs/tenant.md
- app/tests/e2e/docs/trust_registry.md
- app/tests/e2e/docs/verifier.md
- app/tests/e2e/docs/wallet.md
Add break down of all e2e test.
also indicating some missing test
> 📝 e2e test docs

- .github/dependabot.yml
- .github/workflows/cicd.yml
- helm/acapy-cloud.yaml.gotmpl
- helm/nats/Chart.lock
- tilt/acapy-cloud/Tiltfile
- tilt/metrics/Tiltfile
* bitnami/postgresql-ha 15.3.8 -> 15.3.14
* runix/pgadmin4 1.36.0 -> 1.38.0
* bitnami/nats 9.0.7 -> 9.0.11
* bitnami/metrics-server 7.4.1 -> 7.4.2
* Mise 2025.3.7 -> 2025.4.7
* Helm 3.17.2 -> 3.17.3
> :arrow_up: Update Mise, Helm, Postgres

- .github/workflows/cicd.yml
* Don't trigger CICD if the only change was to Dependabot config
> :construction_worker: Ignore changes to `dependabot.yml`

- .github/dependabot.yml
* Split Python and Golang Dockerfiles
> :construction_worker: Dependabot split Python and Golang Dockerfiles

- app/models/definitions.py
- app/routes/definitions.py
- app/services/definitions/schemas.py
- app/tests/fixtures/definitions.py
- app/tests/routes/definitions/test_create_schema.py
- app/tests/services/definitions/schemas/test_create_schemas.py
:fire: Drops Indy schema support
> :lock: Restrict schema creation to governance

- docs/openapi/tenant-admin-openapi.json
- docs/openapi/tenant-admin-openapi.yaml
- docs/openapi/tenant-openapi.json
- docs/openapi/tenant-openapi.yaml
- pyproject.toml
- shared/constants.py
Updates openapi specs and sets project version to 5.0.0rc1
> :bookmark: 5.0.0rc1

- scripts/k6/compose.yaml
- scripts/k6/libs/functions.js
Minor changes to remove indy and support anoncreds.
> ✅ K6 anoncreds

- .github/dependabot.yml
* Saturday 07:00 for all dependabot actions
> :construction_worker: :wrench: Sync dependabot schedules

- scripts/k6/compose.yaml
- scripts/k6/libs/functions.js
- scripts/k6/scenarios/create-invitations.js
- scripts/k6/scenarios/create-proof.js
- retry logic for get referent
- improved logging for generic retry function
- drop connections in favour of DID exhange
> ✅ K6 minor refactor

- .github/workflows/README.md
- .github/workflows/cicd.yml
- .github/workflows/deploy-test-eks.yml
- .github/workflows/docker-build.yml
- .github/workflows/format.yml
- .github/workflows/local-tests.yml
- .github/workflows/notify.yml
- .github/workflows/unit.yml
- .mise.toml
- dockerfiles/agents/Dockerfile
- Move from monolithic workflow to reusable workflow components
- Extract job definitions into dedicated workflow files:
- `format.yml` - Code formatting checks
- `unit.yml` - Unit test execution
- `docker-build.yml` - Container image building
- `local-tests.yml` - Local testing environment
- `deploy-test-eks.yml` - EKS deployment and testing
- `notify.yml` - Notification system
- Replace hardcoded tool versions with parameterized inputs
- Add `workflow_call` inputs and outputs for better component integration
- Maintain existing job dependencies and execution order
- Improve secret handling between workflow components
This refactoring reduces duplication, improves maintainability, and makes workflows easier to test individually.
> :construction_worker: Refactor GitHub Actions workflows

- app/models/revocation.py
- app/models/verifier.py
- app/routes/revocation.py
- app/routes/verifier.py
- app/services/verifier/acapy_verifier_v2.py
- app/tests/services/verifier/test_acapy_verifier_v2.py
- app/tests/services/verifier/test_verifier.py
- docs/openapi/tenant-openapi.json
- docs/openapi/tenant-openapi.yaml
:tada: No more references to "indy" in the OpenAPI specs!
> :art: Rename IndyNonRevocationInterval model

- .github/workflows/README.md
With the EKS workflow refactor the CICD flow chart needed an update
> :memo: Update CICD flow chart

- .mise.toml
Add JSON (jq) and YAML (yq) processing tools to the mise configuration.
These command-line utilities help with parsing and transforming JSON and
YAML files, which are required by `./scripts/download_openapi_specs.sh`
> :wrench: Add jq and yq tools to mise configuration

- scripts/k6/libs/auth.js
- scripts/k6/libs/functions.js
- scripts/k6/libs/issuerUtils.js
- scripts/k6/libs/schemaUtils.js
- scripts/k6/libs/setup.js
- scripts/k6/scenarios/create-creddef.js
- scripts/k6/scenarios/create-credentials.js
- scripts/k6/scenarios/create-holders.js
- scripts/k6/scenarios/create-invitations.js
- scripts/k6/scenarios/create-proof.js
- scripts/k6/scenarios/create-schemas.js
- scripts/k6/scenarios/delete-holders.js
- scripts/k6/scenarios/delete-issuers.js
- scripts/k6/scenarios/revoke-credentials.js
> ✅  K6: authentication strategy

- app/models/tenants.py
- app/tests/models/test_tenants.py
Remove space from `re.match` for `group_id`
Closes #1556
Not gonna update openapi spec. We want to test bots PR
> :bug:  Update `group_id` validation

- app/routes/connections.py
- app/routes/oob.py
- app/services/onboarding/issuer.py
- app/services/onboarding/util/register_issuer_did.py
- app/services/onboarding/verifier.py
- app/tests/e2e/test_oob.py
- app/tests/routes/connections/test_create_did_exchange_request.py
- app/tests/routes/connections/test_delete_connection.py
- app/tests/routes/connections/test_get_connections.py
- app/tests/routes/oob/test_create_oob_invitation.py
- app/tests/services/onboarding/test_onboarding.py
- app/tests/util/connections.py
- docs/src/examples/4. Create Connection with Issuer.md
- docs/src/examples/5. Issue Credential.md
- docs/src/examples/6. Create Connection with Verifier.md
From 1.0 to 1.1
In creating OOB connections, in tests, and in docs
Relates to debugging cheqd connections
> :wrench: Update default didexchange protocol

- helm/acapy-cloud/conf/dev/did-resolver.yaml
* Use the internal k8s service directly
> :wrench: Update Cheqd Testnet Endpoint

- .github/workflows/deploy-test-eks.yml
Bump to latest commit
Includes latest update to Tailscale action which introduces retry logic, improving tailscale stability
> :arrow_up: Bump `didx-xyz/workflows/connect-eks`

- .github/workflows/cicd.yml
- .github/workflows/deploy-test-eks.yml
* Bump Mise to 2025.6.0
* Bump Helm to 3.18.2
* Bump Helmfile to 1.1.1
> :arrow_up: Update Mise, Helm, and Helmfile

- .github/workflows/cicd.yml
- .github/workflows/deploy-test-eks.yml
Ability to skip deployments and run selected tests when using `Deploy and Test EKS` workflow.
> 👷 Run EKS tests in isolation

- scripts/k6/compose.yaml
- scripts/k6/libs/functions.js
- scripts/k6/scenarios/create-credentials.js
- scripts/k6/scenarios/create-invitations.js
- scripts/k6/scenarios/create-proof.js
- scripts/k6/scripts/collection_batch.sh
- follow established naming conventions for SSE URL path constituents
- remove unnecessary use of `const` and programatically set K6 check message
- clean up unused parameters and variables in `genericPolling`
- add custom logging to `genericPolling`
> ✅ K6 refactor generic polling

- helm/acapy-cloud/values.yaml
* Set Istio Sidecar log level to Warning
> :mute: Tweak Istio Sidecar log levels

- dockerfiles/agents/Dockerfile
Reduces log level of unnecessary warning logs
> :arrow_up: Upgrade acapy base image

- tails/routers/tails.py
Improve performance by validating the AnonCreds tails file header
('00 02') during the first chunk read instead of after processing
the entire file. This eliminates the need to seek back to the
beginning of the temporary file for validation.
Changes:
* Move header validation from post-processing to first chunk read
* Add `first_chunk` flag to track initial chunk processing
* Update docstrings to be more specific about AnonCreds tails files
This optimization reduces I/O operations and provides faster feedback
for invalid files, improving overall upload performance.
> :zap: Check Tails File header early

- app/tests/fixtures/credentials.py
- dockerfiles/agents/Dockerfile
- docs/openapi/tenant-openapi.json
- docs/openapi/tenant-openapi.yaml
- shared/models/connection_record.py
Upgrades acapy base image which includes fix for https://github.com/openwallet-foundation/acapy/issues/3792
Includes fixes for Connection Record state enum, which had some incorrect values for rfc23 states.
> :bug: Fix inefficient revocation

- app/tests/e2e/test_sse.py
- scripts/k6/libs/functions.js
- scripts/k6/scenarios/create-invitations.js
Test getting events multiple times 
When creating connections in k6 wait for events on `invitation_msg_id` field
> ✅ Test sse events and update k6

- helm/acapy-cloud/conf/dev/governance-web.yaml
- helm/acapy-cloud/conf/local/governance-web.yaml
Enhance the Governance DID bootstrapping script with more robust error
handling and improved reliability:
* Remove `-e` flag from `set` to allow manual error handling
* Add `-f` flag to `curl` commands for fail-fast behavior on HTTP errors
* Explicitly check curl command exit codes and exit on failure
* Simplify DID existence check by comparing against empty array `[]`
* Define `BASE_URL` variable inline instead of using environment variable
* Add descriptive error messages for debugging failed operations
This prevents silent failures during DID bootstrap and provides clearer
feedback when errors occur, making the deployment process more reliable.
> :wrench: Improve DID bootstrap error handling

- helm/cheqd/Chart.yaml
- helm/cheqd/conf/localnet/values.yaml
In prep for the upcoming Testnet upgrade
> :arrow_up: Cheqd v4.1.4

- helm/nats/values.yaml
- resources/connect-processors/cloud/pipelines/registry-monitor.yaml
Move the registry monitor events to `cloudapi_aries_events` stream
> ⚡️ Update monitor subject

- docs/src/Cheqd.md
Show how to rotate keys and import/add DID to wallet
> 📝 Cheqd DID docs
