didx-xyz/acapy-cloud

app/dependencies.py, app/main.py, app/tests/test_dependencies.py
So this is a poc at this stage.
It uses the x_role header to switch to the relevant agent.
So not sure if there are existing end points (in development branch) that use a token to authenticate so not sure if I can actually use this new fast api depends function. But suffice to say when the end point is shared the following will be used...
```
@router.get("/shared-endoint", tags=["did"])
async def get_api_call_that_works_on_both_member_and_ecosystem(
aries_controller: AriesAgentControllerBase = Depends(ecosystem_or_member_agent),
):
```
see other comments inline
UPDATE: promoted from poc - now becomes the real code
=> Selecting agent based on role

app/main.py, app/tests/test_exception_handler.py
ClientResponseError is what is sent back by the arise cloud controller.
Currently we just return 500 when we get an error in cloud controller as we don't handle this exception. This change will modify things so that we do handle this exception elegantly.
=> added error handler for dealing elegantly with ClientResponseError

app/requirements.txt
No breaking changes but fixes the issues you had with the `-1` validation for revocation and also fixes the fixme's in #165
Signed-off-by: Timo Glastra <timo@animo.id>
=> chore: update cloud-controller to 0.3.2

.github/workflows/continuous-build.yml, Makefile, manage
Replace it by checking the logs of one of the aca-py containers for signalling ready.
Best I could come up with for now. That's what works for me on local machine. 
Happy if there are better suggestions. Couldn't find any poll events to look for in particular as suggested in the ticket.
closes #174
=> Remove inital wait/sleep in github actions.

.github/workflows/continuous-build.yml
CI was being run twice for every PR on a branch that starts with feature/*
=> ci: do not run on feature branch

app/admin/schemas.py, app/tests/e2e/test_schemas.py
Integrates the schema endpoint with the trust registry. When a schema is created, it is automatically added to the trust registry.
In addition this endpoint also removes the /list/ and update schema endpoint. I don't think they're explicitly needed. Especially the update schema adds complexity that is better handled outside of the cloud api (currently).
Fixes https://github.com/didx-xyz/aries-cloudapi-python/issues/141
=> feat: integrate schema endpoint with trust registry

app/main.py, environments/trustregistry/trustregistry.default.env, environments/webhooks/fastapi.webhooks.env, environments/yoma-ga/fastapi.default.env, environments/yoma-multitenant/fastapi.default.env, trustregistry/main.py, webhooks/main.py
As requested by lohan this adds custom names to the open api interface.
This makes it easier to spot what backend one is talking to.
closes #209
=> feat: open api naming

app/admin/tenants/onboarding.py, app/admin/tenants/tenants.py, app/constants.py, app/generic/definitions.py, app/role.py, app/tests/conftest.py, app/tests/e2e/test_tenants.py, app/tests/e2e/test_trust_registry_integration.py, app/tests/test_dependencies.py, app/tests/util/client.py, app/tests/util/client_fixtures.py, app/tests/util/constants.py, app/tests/util/ecosystem_personas.py, app/tests/util/member_personas.py, app/tests/util/tenants.py, environments/governance-ga/fastapi.default.env, environments/governance-multitenant/fastapi.default.env, webhooks/main.py
Combines the member and ecosystem roles into a single tenant role. Permissions are determined by the trust registry rules. 
Nest step is extracting the trust registry  / yoma specific code into a separate module. I'd like to have a discussion about this friday as there's a few approaches we could take here with different implications.
=> refactor: combine member and ecosystem roles

shared_models/shared_models.py
This shouldn;t be neccessary but Aca-py (wrongly) returns None for state
in webhooks sometimes.
=> fix: relax model validation on state attribute.

app/admin/tenants/onboarding.py, app/facades/revocation_registry.py, app/generic/definitions.py, app/listener.py, app/main.py, app/tests/admin/test_onboarding.py, app/tests/conftest.py, app/tests/e2e/conftest.py, app/tests/e2e/test_definitions.py, app/tests/e2e/test_fixtures.py, app/tests/e2e/test_issuer.py, app/tests/e2e/test_tenants.py, app/tests/e2e/test_trust_registry_integration.py, app/tests/e2e/test_verifier.py, app/tests/util/client_fixtures.py, app/tests/util/ecosystem_personas.py, app/tests/util/event_loop.py, app/tests/util/member_personas.py, app/tests/util/webhooks.py, app/webhooks.py
The webhooks + listener implementation (`app/webhook_listener.py`) is laden with code smells:
- poor function names (`on`/`off`; `on_webhook` in listeners and `_on_webhook` in Webhooks class; `_listeners` is the name for the list of callback functions) with no docstring descriptions
- `sys.exit()` being called on timeout errors
- listener is implemented as an `async def start_listener()` which returns two async functions when called: `return wait_for_event_with_timeout, stop_listener`. This should be moved to its own class, providing instance specific access to these methods.
- `while True` to read from an async queue. By default, `get()` from an async queue will wait indefinitely if it's empty. There is also a duplicate method to introduce timeout to this loop
- the match payload to …
=> Improve webhooks + listener implementation

app/admin/tenants/onboarding.py, app/requirements.txt, app/tests/e2e/test_verifier.py, dockerfiles/agents/Dockerfile, dockerfiles/agents/Dockerfile.agent, dockerfiles/agents/Dockerfile.author.agent, endorser/requirements.txt, webhooks/requirements.txt
0.8.1 breaks v1/v2 accepting of proof request OOB. Those tests are being skipped and will be fixed in the future.
=> Upgrade ACA-Py agents to 0.8.1

app/admin/tenants/tenants.py, app/tests/e2e/test_verifier.py
Some `delete_wallet` operations were missing named arguments, which is required.
Additionally, we can now unskip the tests that were previously broken with the 0.8.1 upgrade: in e2e/test_verifier:
- test_accept_proof_request_oob_v1
- test_accept_proof_request_oob_v2
These tests now pass again, so something was fixed in the 0.8.1 -> 0.8.2 updates to resolve the verkey routing issue.
=> Fix accept proof OOB tests and fix delete wallet requests

app/admin/tenants/onboarding.py, app/util/retry_method.py
Onboarding an issuer with no public DID can fail (approx 1% chance) when creating a connection with the endorser. If something goes wrong (e.g. configuring the endorsement or registering did), the whole process should be re-attempted.
=> Add retry logic for onboarding an issuer with no public DID

app/tests/util/ecosystem_connections.py, app/tests/util/member_wallets.py
Made Bob a tenant, no longer a issuer.
Remove webhook check state for endorsments
=> Fix: make `bob_member` test fixture a regular tenant

SECURITY.md, app/models/tenants.py, app/routes/connections.py, app/routes/verifier.py, app/services/onboarding.py, app/services/revocation_registry.py, app/tests/e2e/test_jsonld.py, app/tests/services/test_revocation_registry.py, app/tests/verifier/utils.py, app/util/acapy_verifier_utils.py, scripts/ngrok-wait.sh, webhooks/clients.example.py
- Made long strings multi line
- escaped some brackets in SECURITY.md
- Logging a warning in `accept_proof_request` if `assert_valid_prover`  is not called. Looks like if proof request does not have a `connection_id` it is treated as a `oob` connection
- Removed a duplicate class `WalletRecordWithGroups` in `app/models/tenants.py` 
- Renamed locally scoped variable `cred_ex_id` to `cred_ex_id_b` not to confuse it with global `cred_ex_id` in `test_revocation_registry.py`
- Move `OnboardResults` class to `models/tenants.py`
- renamed instances of the Verifier V1/V2 interface from `prover` to `verifier`
=> Fix todos and address some security issues

app/models/issuer.py, app/models/tenants.py, app/models/verifier.py, app/routes/admin/tenants.py, app/routes/verifier.py, app/services/issuer/acapy_issuer_v1.py, app/services/issuer/acapy_issuer_v2.py, app/services/verifier/acapy_verifier.py, app/services/verifier/acapy_verifier_v1.py, app/services/verifier/acapy_verifier_v2.py, app/tests/e2e/test_trust_registry_integration.py, app/tests/e2e/test_verifier.py, app/tests/services/verifier/test_acapy_verifier_v1.py, app/tests/services/verifier/test_acapy_verifier_v2.py, app/tests/verifier/test_verifier.py, app/tests/verifier/utils.py, app/util/acapy_verifier_utils.py, app/util/tenants.py, docs/Common Steps.md
Introduces DIF models (DIFProofRequest and DIFPresSpec) to the create, send, and accept proof request verifier routes. Adds support for JSON-LD and JWT VCs.
To do: refactor issuer/verifier tests (to distinguish indy-specific tests) and add more expansive ld-proof test cases.
=> Refactor verifier models, service and routes to support jsonld

app/tests/e2e/test_issuer.py, shared/models/topics/base.py
Removed retrieve issued credential issue section because the response will always be empty since the agent does not preserve records.
`ACAPY_PRESERVE_EXCHANGE_RECORDS=false`
Getting `credential_id` from Faber's  'credential offer' and revoke on that id
=> Fix test revoke credential

README.md, docker-compose.yaml, scripts/test_runner.sh
Added a `tests` container and wrapper that can be used to run a specific test until `x` completions or failure without changing the existing loop behaviour of `tests` (where every iteration is a clean start).
=> Chain smoke

app/services/onboarding.py, app/tests/admin/test_onboarding.py, app/util/assert_connection_metadata.py
When onboarding an issuer that does not yet have a public did, a connection first needs to be created between the endorser and the to-be issuer.
Setting up the endorser connection metadata happens asynchronously in ACA-Py, and takes some moments to complete after `set_endorser_role` responds with a success. This leads to some race conditions, where the subsequent `set_endorser_info` method is called too quickly, because the connection metadata has not yet completely updated in ACA-Py storage.
So, it is necessary to assert that roles have been set (in the connection metadata) before the 'info' can be set, and all of this needs to be set before the issuer's did can be registered on the ledger.
This PR adds assert methods in the onboarding logic for an issuer, such that the race condition is …
=> :bug: Fix ACA-Py race condition in configuration of endorser connection

.github/workflows/continuous-deploy.yml
Helm `3.13.3` doesn't exist... How did the CI/CD succeed earlier?
=> Hotfix: Helm `3.13.1`

.github/workflows/continuous-deploy.yml
This will make it so that dependabot PRs won't trigger EKS deployments.
Merging a PR will still trigger deployments to EKS.
=> Skip deploy to EKS if dependabot

environments/governance-ga/aca-py-agent.default.env, environments/governance-multitenant/aca-py-agent.default.env
=> :sparkles: add multitenancy-config for askar wallets

app/event_handling/sse_listener.py, app/services/sse.py, app/services/trust_registry.py, app/tests/conftest.py, app/tests/e2e/test_exception_handler.py, app/tests/services/test_trust_registry.py, app/tests/util/ledger.py, app/tests/util/webhooks.py, endorser/endorser_processor.py, endorser/tests/test_endorser_processor.py, shared/util/rich_async_client.py, trustregistry/tests/test_actor.py, trustregistry/tests/test_main.py, trustregistry/tests/test_schema.py, webhooks/tests/test_sse.py, webhooks/tests/test_webhooks.py
:sparkles: replaces all uses of httpx.AsyncClient with our RichAsyncClient, which provides reusing of SSL certs, and improved error handling.
Other minor improvement: in endorser processor, we fetch actors from the trust registry to assert they are an issuer. If some internal server error occurs when calling trust registry, we will now retry 5 times before failing to assert
=> :sparkles: Reuse SSL cert context for all HTTP requests

app/models/tenants.py, app/requirements.txt, app/routes/admin/tenants.py, app/routes/definitions.py, app/routes/issuer.py, app/routes/jsonld.py, app/services/acapy_ledger.py, app/services/onboarding/issuer.py, app/services/onboarding/tenants.py, app/services/onboarding/util/register_issuer_did.py, app/services/onboarding/util/set_endorser_metadata.py, app/services/onboarding/verifier.py, app/services/revocation_registry.py, app/tests/admin/test_onboarding.py, app/tests/e2e/test_tenants.py, app/tests/e2e/test_trust_registry.py, app/tests/services/test_acapy_ledger.py, app/tests/services/test_revocation_registry.py, app/tests/util/tenants.py, app/util/tenants.py, docs/Governance as Code.md, endorser/requirements.txt, webhooks/requirements.txt
:sparkles: wallet_name can now optionally be included in create tenant request, and used to fetch wallet
:art: adds descriptions and better examples for some fields in create and update tenant requests. Renamed tenant "name" to `wallet_label`, and clarify in description that this name is used as alias in connection records
- raise 409 if wallet_name already exist
- wrote test to assert
- and to assert fetch by wallet name works
- fixed exception handling re new ApiException raised in cloudcontroller, instead of old ClientResponeError
- note: bug in cloudcontroller or our group plugin seems to still return all wallets when fetching wallet_name. No matter. We postprocess results to filter by wallet_name
=> :sparkles: add wallet_name to create tenant request, and allow fetch by wallet_name

app/models/tenants.py, app/routes/admin/tenants.py, app/tests/e2e/test_tenants.py, shared/models/trustregistry.py
Wallet label must be alphanumeric, may contain spaces, and the following special characters are allowed: `.!@$*()~_-`. The same applies for wallet_name. 
We also introduce a max length to these fields of 100 characters.
:white_check_mark: includes tests to assert these changes
=> Disallow special characters in `wallet_label` and `wallet_name`, and limit max length

scripts/aurora-delete.sh
Forcefully drop db's, to circumvent the following error in deploy to EKS job:
```
[2023-11-30T11:37:56+0000]: INFO: Dropping database: ***
ERROR:  database "***" is being accessed by other users
DETAIL:  There are 2 other sessions using the database.
Error: Process completed with exit code 1.
```
=> :hammer: Update script for drop db

app/models/issuer.py, app/services/issuer/acapy_issuer.py, app/services/issuer/acapy_issuer_v1.py, app/services/issuer/acapy_issuer_v2.py, app/tests/e2e/test_credentials.py
`auto_remove` allows the issuer to control whether exchange records are automatically deleted or not. The default environment behavior is not to preserve exchange records (i.e. automatically deleted), and this allows the issuer to override this default behavior, if they request `save_exchange_record=True`.
=> :sparkles: Add `save_exchange_record` argument to send credentials

app/models/connections.py, app/routes/connections.py, app/services/verifier/acapy_verifier_v1.py, app/tests/e2e/test_connections.py, docker-compose.yaml, environments/governance-ga/aca-py-agent.default.env, environments/governance-multitenant/aca-py-agent.default.env
Resolves #518
Identified bug in ACA-Py ([aries-cloudagent-python/#2649](https://github.com/hyperledger/aries-cloudagent-python/issues/2649)), where `auto_accept=True`, used in receiving an invitation, does not override the default environment config of auto_accept_invite/requests = false. Because we use auto_accept=True everywhere, I canged the default env config to auto_accept_invite/requests = true.
Additionally, expanded test coverage for connections using public did.
=> :white_check_mark: Fix creating connections with `use_public_did`

webhooks/dependencies/sse_manager.py, webhooks/dependencies/websocket.py, webhooks/main.py, webhooks/routers/receive_events.py, webhooks/tests/test_receive_events.py, webhooks/tests/test_sse_manager.py
in order to run cluster in high availability.
Moves websocket publishing logic to SSE manager, where events are retreived from redis via pubsub notification. This means all the events that are added to SSE queue (previously made to be stateless using redis pubsub) will now also be published to websocket endpoint.
Resolves #560
=> :sparkles: make websocket event publishing stateless

.github/workflows/continuous-deploy.yml
Resolves the trailing `}` in concurrency group names
=> chore: Remove erroneous close swirly in github action

.github/workflows/continuous-deploy.yml
Add `${{ github.ref }}` to concurrency group for image builds
Will prevent PR's from cancelling each other's builds
=> Patch concurrency group

.github/workflows/continuous-deploy.yml
If commit/PR author is `dependabot[bot]` but one of us re-run a workflow (e.g: failed jobs) then we're the triggering actor
=> `triggering_actor` -> `actor`

.github/workflows/continuous-deploy.yml, app/routes/admin/tenants.py, app/routes/connections.py, app/routes/definitions.py, app/routes/issuer.py, app/routes/jsonld.py, app/routes/messaging.py, app/routes/oob.py, app/routes/sse.py, app/routes/trust_registry.py, app/routes/verifier.py, app/routes/wallet/credentials.py, app/routes/wallet/dids.py, app/routes/webhooks.py, app/tests/test_main.py, docs/Common Steps.md, docs/Governance as Code.md, docs/Webhooks.md, docs/examples/1. Onboarding.md, docs/examples/2. Create Schema.md, docs/examples/3. Create Credential Definition.md, docs/examples/4. Create Connection with Issuer.md, docs/examples/5. Issue Credential.md, docs/examples/6. Create Connection with Verifier.md, docs/examples/7. Verify Credential.md
Changes Made
- API Versioning Introduced: All endpoints now include a `/v1` prefix
- Removal of `/generic` prefix: The `/generic` prefix has been removed from all endpoints where it was previously used.
=> :sparkles: add `/v1` prefix to endpoints, and drop `/generic`

.github/workflows/continuous-deploy.yml
* `mdgreenwald/mozilla-sops-action@v1.5.0` -> `1.6.0`
This gets rid of
> [Deploy to EKS](https://github.com/didx-xyz/aries-cloudapi-python/actions/runs/8185142066/job/22380921256)
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: mdgreenwald/mozilla-sops-action@v1.5.0. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
=> Bump Mozilla sops action

.github/workflows/continuous-deploy.yml
* Redis CLI needs TLS, Auth, and Clustered
* Pin `MishaKav/pytest-coverage-comment` to `v1.1.51`
* Fix typo in `Publish Test Report` step
* Only run `Pytest coverage comment` when a PR
=> Enable Redis TLS, Auth, and Clustered in GH Actions

app/tests/e2e/test_tenants.py, app/util/tenants.py
Resolves #567
With the group_id plugin changes (appending group_id to wallet record settings), this could now be easily resolved.
=> :bug: fix missing group_id in update/get_tenant response

endorser/services/endorsement_processor.py, endorser/tests/test_endorser_processor.py, webhooks/services/acapy_events_processor.py, webhooks/tests/test_acapy_events_processor.py
pubsub listeners are currently unused in endorsement and acapy events processor. 
The code exists because it will be more elegant to wait for notifications before scanning redis. Currently we just continuously scan redis to avoid missing notifications, because it needs to be confirmed that notifications works reliably with cluster config.
In our test env, the redis pubsub channels disconnect after 1h, for some currently unknown reason, and then healthcheck causes pods to restart. 
This patches that behavior so pubsub connections aren't initialised or checked in healthcheck
=> :adhesive_bandage: disable pubsub notification listener in events processors

app/util/retry_method.py, shared/log_config.py, shared/models/endorsement.py, shared/services/redis_service.py, webhooks/services/acapy_events_processor.py, webhooks/services/webhooks_redis_serivce.py, webhooks/tests/test_acapy_events_processor.py, webhooks/tests/test_redis_service.py
Two webhook event topics were identified to possibly contain sensitive data:
`endorsement` events, and `issue_credential_v2_0_indy` events.
Endorsements can either contain a `messages_attach`, or `signature_response` object in the payload, which contains a json string that references a `master_secret` value. The exact nature of this value, and whether it is truly sensitive data, is not yet fully known, but for simplicity we redact these values from logs.
Similarly, `issue_credential_v2_0_indy` events contain a `master_secret_blinding_data` field in the `cred_request_metadata`. For simplicity, we redact these values as well.
Lastly, loguru sinks take a `diagnose` field, which impacts whether values are printed in exception stack traces or not. To prevent sensitive data from leaking in …
=> :sparkles: obfuscate secret data from webhook logs

dockerfiles/agents/Dockerfile.agent, dockerfiles/agents/Dockerfile.author.agent, shared/models/endorsement.py, webhooks/services/acapy_events_processor.py, webhooks/services/webhooks_redis_serivce.py
Resolves double endorsement issue when running with more than one endorser replica. 
Fixes duplicate webhook events in general! 
Primary change in our custom redis-events plugin: https://github.com/didx-xyz/aries-acapy-plugins/pull/114
=> :bug: Fix double endorsement

app/routes/webhooks.py, app/services/webhooks.py, webhooks/services/webhooks_redis_serivce.py, webhooks/tests/test_redis_service.py, webhooks/web/routers/webhooks.py
Marks /webhooks endpoint as deprecated, with comment to recommend SSE / websockets instead.
Refactors fetching logic to ensure maximum of 100 events are returned, so as to not overload responses.
=> :wastebasket: Deprecate webhooks endpoint

.github/workflows/continuous-deploy.yml
* Cache from the `latest` tag
* Skips building images from scratch that had no changes
* In the future we'll add change detection so we only build images that
actually need to be built
=> Speed up Docker Builds

.github/workflows/continuous-deploy.yml
Realized after merging #710 that we don't actually have a `latest` tag
* Push `latest` docker tag if `github.ref` is the default git branch
=> Push `latest` if on default branch

webhooks/services/sse_manager.py, webhooks/services/webhooks_redis_serivce.py, webhooks/tests/test_redis_service.py, webhooks/tests/test_sse_manager.py, webhooks/web/routers/sse.py, webhooks/web/routers/websocket.py
Adds assertion logic to SSE routes, so that if a group_id exists in the query parameters. we assert using redis keys that the wallet does in fact belong to that group. We raise a 403 otherwise.
=> :sparkles: Validate wallet_id belongs to group_id in SSE subscriptions

app/tests/e2e/issuer/indy/test_v1_indy.py, app/tests/e2e/issuer/indy/test_v2_indy.py, app/tests/e2e/issuer/ld_proof/test_ld_proof_did_key_bbs.py, app/tests/e2e/issuer/ld_proof/test_ld_proof_did_key_ed25519.py, app/tests/e2e/issuer/ld_proof/test_ld_proof_did_sov.py, app/tests/e2e/issuer/test_connections_use_public_did.py, app/tests/e2e/issuer/test_save_exchange_record.py, app/tests/e2e/test_connections.py, app/tests/e2e/test_oob.py, app/tests/e2e/test_proof_request_models.py, app/tests/e2e/verifier/test_proof_revoked_credential.py, app/tests/e2e/verifier/test_verifier.py, app/tests/test_util_webhooks.py, app/tests/util/credentials.py, app/tests/util/ecosystem_connections.py, app/tests/util/webhooks.py
Replaces usages of SseListeners in tests with the helper "check_webhook_state" method. 
Implemented some basic retry logic in this helper method. Currently configured to retry on HTTP disconnects once.
=> :sparkles: Configure SseListeners in tests with retry logic

app/routes/websocket_endpoint.py, app/services/event_handling/websocket_manager.py, app/services/websocket.py, app/tests/services/event_handling/test_websocket_manager.py, webhooks/services/sse_manager.py, webhooks/services/webhooks_redis_serivce.py, webhooks/tests/test_redis_service.py, webhooks/tests/test_sse_manager.py, webhooks/web/routers/websocket.py
Modified internal websocket publish-topics to support group_id.
`group_id` is now an optional query parameter for websocket endpoints
:sparkles: Additional route:
- `@router.websocket("/v1/ws/")`
- Takes group_id as query param and subscribes to all wallets in group
=> :sparkles: add group_id to websocket subscriptions

app/routes/sse.py, app/services/sse.py
Add group_id query parameter for the tenant-web / tenant-admin-web SSE endpoints, and forward group_id param as part of the request to the webhooks service
=> :sparkles: Add `group_id` query parameter to SSE endpoints

app/routes/sse.py, app/services/event_handling/sse.py, app/tests/e2e/issuer/indy/test_v1_indy.py, app/tests/e2e/issuer/indy/test_v2_indy.py, app/tests/e2e/issuer/ld_proof/test_ld_proof_did_key_bbs.py, app/tests/e2e/issuer/ld_proof/test_ld_proof_did_key_ed25519.py, app/tests/e2e/issuer/ld_proof/test_ld_proof_did_sov.py, app/tests/e2e/test_proof_request_models.py, app/tests/e2e/verifier/test_proof_revoked_credential.py, app/tests/e2e/verifier/test_verifier.py, app/tests/routes/test_sse.py, app/tests/services/event_handling/test_sse.py, app/tests/test_util_webhooks.py, app/tests/util/ecosystem_connections.py, app/tests/util/sse_listener.py, app/tests/util/webhooks.py, shared/constants.py, webhooks/services/sse_manager.py, webhooks/web/routers/sse.py
Internal changes: 
- `lookback_time` renamed to `look_back`
- changed from float to int
- updated tests
External changes:
- `look_back` now an available query param on SSE routes
- `group_id` query param is now hidden from swagger docs (because it shouldn't be set)
=> :sparkles: add `look_back` query param to SSE routes

app/routes/admin/tenants.py, app/routes/sse.py, app/routes/websocket_endpoint.py, app/services/onboarding/tenants.py, app/tests/e2e/test_tenants.py, app/util/tenants.py, webhooks/web/routers/sse.py
Now that we are entering the world of tenants belonging to various groups, we should enforce that tenant-admins do not have global privileges, and can only act on wallets in their group.
`group_id` is now a _hidden_ query param added to each tenant route, where we raise a 404 if the wallet attempted to be acted upon does not belong to the tenant-admin's group
=> :lock: Forbid wallet actions if wallet doesn't belong to group

app/main.py
Our `cloud_api_docs_description` for the Swagger docs was not being printed for the tenant-admin route. This patches that
=> 📝 Update tenant-admin Swagger docs to include CloudAPI description

app/routes/websocket_endpoint.py, app/tests/services/verifier/test_verifier_utils.py, app/util/acapy_verifier_utils.py, trustregistry/registry/registry_schemas.py
Minor fix, handling the potential case that no schema_ids are found to be associated with an indy proof request. Should never happen, but now we log a warning and invalidate such cases.
Includes some minor fixes for code scanning warnings (re-raising exceptions and fix shadowed method name)
=> :adhesive_bandage: Invalidate proof if no associated schema_ids found

app/services/event_handling/websocket_manager.py
`callback` requires the keyword: topic, which was removed as it's unused in the scope of the function. Whoops :see_no_evil:
=> :adhesive_bandage: Fix WebSocket callback function

.github/workflows/continuous-deploy.yml
If we use `github.ref_name` then we don't need to do the string formatting
=> Make the latest docker tag condition more concise

app/models/tenants.py, app/routes/admin/tenants.py, app/services/onboarding/tenants.py
The following PRs introduced backward incompatibility:
- https://github.com/didx-xyz/aries-cloudapi-python/pull/691/files#diff-f86b437751dbc6d5826f0299bb6c261b071a0e78522efc41c00570d075a2370e
- https://github.com/didx-xyz/acapy-wallet-groups-plugin/pull/34
Summary:
- `group_id` used to be stored as an attribute of a wallet record
- this made that it is not accessible by the redis-plugin, which does not know about the custom group_id
- the group_id was migrated to be stored in wallet settings, so that it's accessible by the redis-plugin
- this meant that wallets created before this update do not have the group_id stored in the new way
This PR introduces a temporary PUT endpoint which will patch old wallets with the correct group_id pattern. The route has a `dry_run` query param to see what …
=> :sparkles: Implement temporary endpoint to patch wallets with old group_id

app/tests/e2e/issuer/test_connections_use_public_did.py, app/tests/e2e/test_oob.py, app/tests/e2e/verifier/test_verifier.py
Previously, sleeps were added to tests using public dids, because the ledger would take some time to reflect. Now the sleeps are no longer necessary
=> ✅ Remove sleeps from public did tests

.github/workflows/continuous-deploy.yml, trustregistry/tests/test_registry_actors.py, trustregistry/tests/test_registry_schema.py
Add unit tests for trust registry endpoints
One line in `trustregistry/registry/registry_actors.py`  (line 54) that I am not able to test. Looks like pydantic wont allow to happen
=> Test trust registry endpoints

docker-compose.yaml, resources/nats-local.conf
➕ Adds [NATS Jetstream](https://docs.nats.io/nats-concepts/jetstream) cluster to docker compose for local dev to support durable event streaming
=> Add nats jetstream cluster for local dev with persistent storage

app/main.py
Pydantic validation errors may not be serializable, causing a 500 to be raised when attempting to handle a 422. This PR extracts the error message from the pydantic validation error as a string, resolve that.
=> :bug: fix ValidationError exception handling

app/services/revocation_registry.py, app/util/credentials.py
Allows our enriched cred_ex_ids (with v1 / v2 prefix) to be passed to revocation service without raising bad requests
=> :sparkles: strip protocol prefix from cred ex id in revocation service

app/models/verifier.py, app/routes/verifier.py, app/services/verifier/acapy_verifier_v1.py, app/services/verifier/acapy_verifier_v2.py, app/tests/e2e/verifier/test_verifier.py, app/tests/services/verifier/test_acapy_verifier_v1.py, app/tests/services/verifier/test_acapy_verifier_v2.py, app/tests/services/verifier/test_verifier.py, shared/models/presentation_exchange.py
If prover does not pass a `problem_report` verifier state does not go to abandoned 
Updated `RejectProofRequest` model to require `problem_report`
closes #782
=> Fix reject proof request

app/models/verifier.py, app/tests/e2e/issuer/test_indy_credentials.py, app/tests/e2e/issuer/test_save_exchange_record.py, app/tests/e2e/verifier/test_proof_revoked_credential.py, app/tests/e2e/verifier/test_verifier.py, app/tests/e2e/verifier/test_verifier_oob.py, app/tests/models/test_verifier.py, app/tests/util/credentials.py, app/tests/util/definitions.py, app/tests/util/verifier.py
Our e2e tests in `app/tests/e2e/verifier/test_verifier.py` could benefit from deduplication -- namely parametrizing by protocol version, so we don't have separate tests for v1 and v2.
=> :art: Cleanup and parametrize verifier tests

app/services/issuer/acapy_issuer_v1.py, app/services/issuer/acapy_issuer_v2.py, app/tests/services/issuer/test_acapy_issuer_v1.py, app/tests/services/issuer/test_acapy_issuer_v2.py
It appears that the initial implementation of deleting a credential exchange record, would go the extra mile and also delete the credential from the wallet. This is a bit an over-eager thing to do if you ask me. Exchange records do not represent the credential itself. So deleting the exchange record should not do anything to the credential in your wallet.
=> :sparkles: Don't delete the credential when deleting credential exchange record

app/models/issuer.py, app/routes/issuer.py, app/services/revocation_registry.py, app/tests/e2e/conftest.py, app/tests/e2e/test_revocation.py, app/tests/e2e/verifier/test_proof_revoked_credential.py, app/tests/fixtures/credentials.py, app/tests/services/issuer/test_issuer.py, app/tests/services/test_revocation_registry.py
The /revoke credential endpoint accepts an unused argument: `credential_definition_id`. This is now removed.
Additionally, e2e test coverage is added for the auto_publish_to_ledger option, which was previously uncovered.
=> 🎨 update revoke credential request body and ✅ add tests with auto-publish true

app/models/definitions.py, app/routes/definitions.py, app/services/revocation_registry.py, app/tests/e2e/test_definitions.py
Update docstrings
:sparkles: modifies the get schemas route to return schemas from trust registry when regular tenants call the endpoint (previously only governance would ever get a result from get_schemas)
:sparkles: now only waits for one active registry to be created, for a revocable cred def to be complete, instead of waiting for both of them
:boom: no longer allows clients to customise the revocation registry size (will always default to max value)
=> Definitions swagger update

docker-compose.yaml, dockerfiles/agents/Dockerfile.agent, dockerfiles/agents/Dockerfile.author.agent
Includes more verbose info logs (https://github.com/didx-xyz/aries-acapy-plugins/pull/419) to debug starting redis cluster with 1 node
=> :arrow_up: update redis events plugin to latest release

app/tests/e2e/test_tenants.py, shared/constants.py
Adds try-finally blocks to ensure that tenants are deleted in edge cases where test failure occurs after tenant creation.
also fixes test that breaks when many wallets exist, since the new pagination feature changed the default behaviour.
also bumps the project version to match aca-py: 1.0.0rc4
=> :white_check_mark: ensure test tenants are deleted upon test failure

shared/services/redis_service.py
Scanning keys should increment the cursor value until the next_cursor value that is returned indicates scan is complete.
Resolves issue where ACA-Py events processor does not receive some keys when many redis records exist with more than one primary node.
=> :bug: Fix scanning of redis keys

app/tests/e2e/issuer/ld_proof/test_ld_proof_did_key_bbs.py, app/tests/e2e/issuer/ld_proof/test_ld_proof_did_key_ed25519.py, app/tests/e2e/issuer/test_save_exchange_record.py, app/tests/e2e/verifier/test_verifier.py, app/util/pagination.py
Problem description: 
- some of our long-running tenants (in regression testing) will continue to generate new connection or proof records
- some of our tests try fetch "all records" (defaulting to fetch 100 records at a time, since the pagination feature was merged)
- when more than 100 records exist, some assertions could now fail
Solution: 
- the known failing tests will now fetch with filtering params, where possible, otherwise we fetch with a limit of 10'000.
- Additionally, I've increased the default pagination limit from 100 to 1'000, mainly to allow some more grace before other tests with increasing records may fail. But also because 100 is not that much.
Note:
- this means the problem can still occur if these regression tenants run long enough to generate >10'000 records.
- so, …
=> :wrench: Increase default pagination `limit` to 1000 and :white_check_mark: fix regression tests when fetching many records

app/services/definitions/credential_definitions.py, shared/constants.py
Set revocation registry size at runtime overriding default max size of `32767` to provide flexibility during testing.
Revocation registry size of `100` speeds up response times significantly:
=> Revoc reg size

.github/workflows/continuous-deploy.yml
On clean start deployment job can take longer than 10 minutes.
=> 👷  Increase deploy timeout

shared/services/redis_service.py, webhooks/services/sse_manager.py, webhooks/tests/services/test_sse_manager.py
Backfilling SSE queues with recent events is currently highly inefficient when many wallets exist. Fortunately this is a non-critical feature, and so can just be removed for now. A solution will be implemented as detailed in https://github.com/didx-xyz/aries-cloudapi-python/issues/899
=> :adhesive_bandage: Remove `_backfill_events` method from webhooks service startup

shared/services/redis_service.py, webhooks/services/acapy_events_processor.py, webhooks/tests/services/test_acapy_events_processor.py
Increases the expiry time of the ACA-Py webhook event locks from 0.5 to 2 seconds, and increases the frequency of the extend lock task.
Resolves #959
=> 🩹 Increase expiry time of redis webhook event locks

.github/workflows/continuous-deploy.yml
Patching the agents with RDS Proxy config is now handled via helm `--state-values-set rdsProxyEnabled=true`.
Removes the need for the patch proxy step which saves some time and reduces overhead.
Also executing "regression" tests before "clean" tests since they take longer.
=> 🧑‍💻 Remove patch proxy CICD logic

app/tests/e2e/issuer/test_save_exchange_record.py, app/tests/e2e/test_wallet_dids.py, app/tests/e2e/verifier/test_verifier.py
`app/tests/e2e/test_wallet_dids.py::test_list_dids` compares the list_dids HTTP response to a direct call of the method.
When tests are run in parallel with `pytest-xdist`, the results can mismatch if another did was created in the interim.
Instead of removing the assertion, we now compare a filtered result.
Resolves #978 
Edit: includes additional sleep of 1s added to `app/tests/e2e/verifier/test_saving_of_presentation_exchange_records` (known bug - it can take a moment for auto-delete of exchange records to take place), which sporadically came up.
=> :white_check_mark: fix test to work with pytest-xdist

app/poetry.lock, endorser/poetry.lock, trustregistry/poetry.lock, webhooks/poetry.lock
Primarily to update `websockets` dependencies, as `fastapi_websocket_pubsub` now supports latest versions
=> :arrow_up: Update lock files

.pre-commit-config.yaml, app/models/issuer.py, app/poetry.lock, app/pyproject.toml, app/routes/issuer.py, app/services/revocation_registry.py, app/tests/e2e/issuer/test_indy_credentials.py, app/tests/e2e/test_revocation.py, app/tests/routes/issuer/test_get_pending_revocations.py, app/tests/routes/issuer/test_publish_revocations.py, app/tests/services/test_revocation_registry.py, app/tests/util/models/dummy_txn_record_publish.py, app/tests/util/webhooks.py, dockerfiles/agents/Dockerfile, dockerfiles/agents/Dockerfile.agent, dockerfiles/agents/Dockerfile.author.agent, endorser/poetry.lock, endorser/pyproject.toml, shared/constants.py, webhooks/poetry.lock, webhooks/pyproject.toml
Enrich revoked responses
- Add get pending revocations endpoint (per registry)
- Publish revocation endpoint now returns cred_rev_ids per rev_reg_id published
- Revoke true will also return cred_rev_ids per rev_reg_id published
- added and fixed tests
Upgrade to Aca-Py v1.0.0
=> :arrow_up: :sparkles:  Upgrade acapy 1.0.0

app/models/issuer.py, app/routes/issuer.py, app/services/revocation_registry.py, app/tests/routes/issuer/test_publish_revocations.py
Address some issues found in v1 update
=> 🦺 🩹  Aca-py V1 update cleanup

tilt/cloudapi/Tiltfile, tilt/cloudapi/nats/Chart.yaml, tilt/cloudapi/nats/templates/job.yaml, tilt/cloudapi/nats/values.yaml, tilt/cloudapi/pgadmin.yaml, tilt/cloudapi/redis-insight.yaml
* Add a Redis Insight deployment to Tilt for local dev
* Speed up PGAdmin readiness
* Optimize NATS Post Install
* Use `bitnami/natscli` docker image to bootstrap NATS
* Means we don't need to use an init container to install the NATS CLI
=> 👷 🧑‍💻 Redis-Insight in Tilt

tilt/cloudapi/Tiltfile, tilt/cloudapi/nats/Chart.lock, tilt/cloudapi/nats/templates/job.yaml
* Bump `bitnami/nats` to `8.4.2` which includes a fix enabling single
replica jetstream
* Also pull `.Values.nats.podAnnotations` to disable Istio Sidecar
Injection on NATS Post-Install/Upgrade
=> 👷 🧑‍💻 Single Replica NATS Jetstream

shared/log_config.py
Fixes the log config by creating a new, empty loguru Logger instance each time. Changes in #1037 caused logger to include default stderr sink as well.
=> :bug: fix log config: create new empty logger for each main module

dockerfiles/agents/Dockerfile.agent, dockerfiles/agents/Dockerfile.author.agent
* Turns out this breaks DDTrace on the agents
=> :rewind: Don't install DDTrace on Agents

dockerfiles/agents/Dockerfile.agent, dockerfiles/agents/Dockerfile.author.agent
DDTrace Profiling complains about missing `google-protobuf` module
=> 🧐 Install Protobuf in Aca-Py Agents

.github/workflows/style-check.yml
* Use Mise to install Python and dependencies to run style checks
* Check Tiltfile formatting
---
This also speeds up the Style Check action from ±20s to ±15s.
Probably because of Mise Caching and `uv` is faster than `pip`
=> :construction_worker: Add Style Check for Tiltfiles

.github/workflows/continuous-deploy.yml, .mise.toml, Tiltfile, tilt/cloudapi/Tiltfile
* Mise update broke argument forwarding
* Changed `tilt:ci` task to always pass `--no-build` to Tiltfile
=> 👷 Fix Tilt CI

.mise.toml, Tiltfile, tilt/cloudapi/Tiltfile, tilt/utils/Tiltfile
Programmatically detect Host IP Address and set Kubernetes Ingress Domain accordingly.
* Detect Tailscale
* Detect Host IP Address
* (Unless CI) set Ingress Domain to `${ip_address}.nip.io`
* Allows for routing to services on Tilt/Kind outside of `localhost` context
* It can be toggled via a button in the Tilt UI
---
Example:
_Tailscale not active_:
* Ingress Domain is `192.168.0.193.nip.io`
* Example ingress: `pgadmin.192.168.0.193.nip.io`
_Tailscale active_:
* Ingress Domain is `100.83.69.38.nip.io`
* Example ingress: `pgadmin.100.83.69.38.nip.io`
To allow connections from within Tailnet to yourself you must [allow incoming connections](https://tailscale.com/kb/1072/client-preferences?q=allow+incoming#allow-incoming-connections).
=> 🧑‍💻 Programmatically detect IP address

.mise/tasks/kind/destroy
When running `mise run tilt:down:destroy`, Mise would leave the Docker
Cache and Kind Registry containers dangling.
Don't do that anymore.
=> 🧑‍💻 Docker remove Kind Registry and Docker Cache

app/main.py, app/poetry.lock, app/pyproject.toml, endorser/main.py, endorser/poetry.lock, endorser/pyproject.toml, trustregistry/main.py, trustregistry/poetry.lock, trustregistry/pyproject.toml, waypoint/main.py, waypoint/poetry.lock, waypoint/pyproject.toml, waypoint/routers/sse.py
* Disable Redoc (it was never officially used anyways)
* Replace Swagger with Scalar
---
✨  It's pretty ✨
=> :heavy_plus_sign: :memo: Disable Redoc, replace Swagger with Scalar

.mise.toml, .pre-commit-config.yaml
* Bump `pre-commit` from `3.8` to `4.0` in `.mise.toml`
* Bump `blacken-docs` commit hook from `1.15.0` to `1.19.0`
=> :arrow_up: Pre-Commit 4.0

scripts/k6/main.js, scripts/k6/scenarios/create-invitations.js, scripts/k6/scenarios/create-issuers.js, scripts/k6/scenarios/create-schemas.js, scripts/k6/scenarios/delete-holders.js
:art: Fixes 8 code scanning warnings:
```
Unnecessary block.
Warning
#7004 opened last month • Detected by Pmd (reported by Codacy) in scripts/.../scenarios/create-invitations.js :79
development
Unnecessary block.
Warning
#6982 opened 2 months ago • Detected by Pmd (reported by Codacy) in scripts/.../scenarios/create-schemas.js :59
development
Unnecessary block.
Warning
#6723 opened 3 months ago • Detected by Pmd (reported by Codacy) in scripts/.../scenarios/create-issuers.js :69
development
Unnecessary block.
Warning
#6636 opened 3 months ago • Detected by Pmd (reported by Codacy) in scripts/.../scenarios/delete-holders.js :63
development
Unnecessary block.
Warning
#5795 opened 4 months ago • Detected by Pmd (reported by Codacy) in scripts/k6/main.js :154
development
Arrow function …
```
=> :art: resolve remaining repo code scanning warnings

.github/workflows/continuous-deploy.yml, .mise.toml
* Bump Helmfile `0.169`
* Bump Helm `3.16.2`
* Bump Tailscale `1.76.0`
=> :arrow_up: Helmfile `0.169`, Helm `3.16.2`, Tailscale `1.76.0`

scripts/k6/Dockerfile
* `xk6-sse` isn't compatible with `k6>=0.53`
* Pin `xk6` and all plugins to the latest compatible versions
* Also bump Golang to `1.23`
=> :pushpin: Pin `xk6` and plugins

scripts/k6/Dockerfile
* Version of k6 being installed was `v0.46.0` which is quite old
* Explicitly pin k6 to `v0.52.0`
=> :pushpin: Explicitly pin k6 to `v0.52.0`

README.md, app/services/acapy_ledger.py, app/tests/e2e/verifier/test_many_revocations.py, app/tests/e2e/verifier/test_proof_revoked_credential.py, dockerfiles/agents/Dockerfile, dockerfiles/agents/Dockerfile.agent, dockerfiles/agents/Dockerfile.author.agent, docs/Aries Cloud API Architecture.md, docs/Governance as Code.md, environments/governance-ga/aca-py-agent.default.env, environments/governance-multitenant/aca-py-agent.default.env, shared/models/endorsement.py
♻️ Synced our fork to latest changes on upstream/main, pulling in our pagination feature: 
https://github.com/didx-xyz/acapy/releases/tag/1.1.1b0
⬆️ Updated acapy-wallet-groups-plugin and our nats_event plugin to use this version too:
- https://github.com/didx-xyz/acapy-wallet-groups-plugin/releases/tag/1.1.1b0
- https://github.com/didx-xyz/aries-acapy-plugins/releases/tag/v1-2024-10-22
- ✨ acapy-plugins repo has also been reset to be up to date with upstream/main, to make future updates easier
- Note: `aries_cloudagent` imports in these plugins have been refactored to use renamed `acapy_agent` package
🎨 Updated docs/links referencing acapy repo to be up to date
=> :arrow_up: Upgrade to our 1.1.1b0 acapy release

dockerfiles/agents/Dockerfile, dockerfiles/agents/Dockerfile.agent, dockerfiles/agents/Dockerfile.author.agent
Relates to https://github.com/openwallet-foundation/acapy/issues/3306
Updates agent base images to use our acapy fork with the fix, released here: 
https://github.com/didx-xyz/acapy/releases/tag/1.1.1b1
ACA-Py PR: https://github.com/openwallet-foundation/acapy/pull/3310
=> :bug: fix DidRotate Hangup error

app/routes/sse.py, app/services/event_handling/sse.py, app/tests/routes/test_sse.py, app/tests/services/event_handling/test_sse.py, app/tests/util/sse_listener.py, waypoint/routers/sse.py, waypoint/services/nats_service.py, waypoint/tests/routers/test_waypoint_sse.py, waypoint/tests/services/test_nats_service.py
Add `deliver_policy` to waypoint `by_start_time`
Removed env var `LOOK_BACK`,  add `look_back` query param to sse endpoints. 
Default `look_back` is 300 seconds
=> :zap: Waypoint start time

shared/util/rich_async_client.py
Since 503 errors can sometimes occur in our EKS tests, this inspired that our RichAsyncClient implementation should be configurable for retries
Current new defaults: up to 3 retries on 503 errors.
=> :sparkles: Implement retry logic in RichAsyncClient

app/main.py, app/tests/test_main.py
Fastapi's ORJSONResponse = JSON response using the high-performance orjson library to serialize data to JSON.
=> :zap: replace FastAPI `JSONResponse` with `ORJSONResponse`

.github/workflows/validate-pr.yml
Add action that validates PR titles.
Currently will print a Warning and leave a comment on the PR if the PR title doesn't start with an emoji.
Comment is left once. If the PR is updated with an emoji, the comment is removed.
=> 👷 Validate PR Title

.github/workflows/validate-pr.yml
* PR Title length should not exceed 50 characters (excluding emojis)
* Emojis are validated against gitmoji.dev
---
=> 👷  Validate PR Title Length

endorser/services/endorsement_processor.py, shared/services/nats_jetstream.py, waypoint/tests/services/test_nats_service.py
=> :bug: Nats reconnect logic

app/tests/e2e/conftest.py, app/tests/e2e/test_wallet_credentials.py, app/tests/fixtures/credentials.py
=> ✅ Test limit and offset params on get credentials

.vscode/extensions.json, docs/Trust Registry.md
Add mermaid to recommended extensions
Add flow charts to show how TR plays a role
=> :memo: Trust registry docs

app/routes/connections.py, app/services/trust_registry/schemas.py, app/tests/e2e/verifier/test_many_revocations.py, app/tests/util/webhooks.py, app/util/acapy_verifier_utils.py, shared/util/rich_async_client.py
Resolves:
- using list as default arg in RichAsyncClient
- ignores "too many arguments" / etc warnings for methods that need it
- fix unused argument in test fixture
- ignore too general exception for tests
- add "raise exception from" in schemas service
The only remaining warnings are todo's (excluding some warnings in tests)
=> :art: Resolve pylint warnings

app/models/wallet.py, app/routes/wallet/dids.py, app/tests/routes/wallet/dids/test_create_did.py
Update `wallet/did` docstrings
Create DID endpoint request model now extends AcaPy model, to flatten `options` field. This brings `key_type` and `did` fields up. 
⚠️ Deprecates the `options` field in the DIDCreate request body, and moves the nested `key_type` and `did` fields up one level.
=> 📝 Update docstrings wallet/dids

app/models/issuer.py, app/models/verifier.py, app/routes/issuer.py, app/services/issuer/acapy_issuer_v2.py, app/services/verifier/acapy_verifier_v2.py, app/tests/e2e/issuer/test_save_exchange_record.py, app/tests/e2e/verifier/test_verifier.py, app/util/save_exchange_record.py
Currently `save_exchange_record` (in issuer and verifier flows) is a bool: True or False. This means that we always override the wallet's default settings. We should support a "None" option as well, which should use the wallet's configuration.
=> :sparkles: `save_exchange_record` should be Optional

app/routes/issuer.py, app/services/issuer/acapy_issuer.py, app/services/issuer/acapy_issuer_v2.py, app/tests/e2e/issuer/test_save_exchange_record.py, app/tests/routes/issuer/test_request_credential.py, app/tests/services/issuer/test_issuer.py, app/util/save_exchange_record.py
New query param for `POST /v1/issuer/{credential_exchange_id}/request`:
`save_exchange_record` to control whether record is preserved from holder's side
=> :sparkles: Add `save_exchange_record` to request_credential

app/routes/wallet/credentials.py
Following up on #814 https://github.com/didx-xyz/aries-cloudapi-python/commit/2bbe2802e684499743aca3fe9fa7fb258ed8f31a#diff-27b2b23e3c1ffda10f6f3faaf140b96793d52066a3842eb2cde84b36e5558eccR236
=> :rewind: Revert change to `list_w3c_credentials` endpoint

.github/workflows/sonarcloud.yml, pyproject.toml
⬆️ Upgrade deprecated `sonarcloud-github-action` to `sonarqube-scan-action`
also:
👷 setup coverage report for SonarCloud (currently no coverage data [here](https://sonarcloud.io/project/overview?id=didx-xyz_aries-cloudapi-python))
🔧 configure coverage exclusion rule (test files can have uncovered lines, so remove them from the count)
=> ⬆️ Upgrade deprecated SonarCloud action

.github/workflows/codacy.yml, .github/workflows/continuous-deploy.yml, .github/workflows/sonarcloud.yml, .github/workflows/style-check.yml, .github/workflows/validate-pr.yml
* Run [zizmor](https://woodruffw.github.io/zizmor) against all our Github actions
* Resolve all failed checks
---
Inspired by https://www.youtube.com/watch?v=MdbhLX67jDY
---
It's mainly resolving [Template Injection](https://woodruffw.github.io/zizmor/audits/#template-injection)
=> :lock: Resolve all failed zizmor checks

app/poetry.lock, app/pyproject.toml, dockerfiles/agents/Dockerfile.agent, dockerfiles/agents/Dockerfile.author.agent, endorser/poetry.lock, endorser/pyproject.toml, trustregistry/poetry.lock, trustregistry/pyproject.toml, waypoint/poetry.lock, waypoint/pyproject.toml
Includes patch upgrades for orjson, protobuf, pydantic, and sqlalchemy
=> :arrow_up: Upgrade anyio and update lock files

.github/workflows/continuous-deploy.yml, .github/workflows/style-check.yml
* Don't trigger CICD if only `docs/**` or a Markdown File was updated
---
Once this is merged, I'll open another PR to verify the `docs/**` and `**.md` exclusion works as expected
=> :construction_worker: Skip CICD on docs

.vscode/settings.json, app/services/onboarding/issuer.py, app/tests/e2e/issuer/ld_proof/test_ld_proof_did_key_bbs.py, app/tests/e2e/issuer/ld_proof/test_ld_proof_did_key_ed25519.py, app/tests/e2e/issuer/ld_proof/test_ld_proof_did_sov.py, app/tests/e2e/issuer/ld_proof/util.py, app/tests/e2e/issuer/test_connections_use_public_did.py, app/tests/e2e/issuer/test_get_records_paginated.py, app/tests/e2e/issuer/test_indy_credentials.py, app/tests/e2e/issuer/test_save_exchange_record.py, app/tests/e2e/test_definitions.py, app/tests/e2e/test_did_exchange.py, app/tests/e2e/test_did_rotate.py, app/tests/e2e/test_jsonld.py, app/tests/e2e/test_oob.py, app/tests/e2e/test_proof_request_models.py, app/tests/e2e/test_revocation.py, app/tests/e2e/test_tenants.py, app/tests/e2e/test_trust_registry.py, app/tests/e2e/test_wallet_credentials.py, app/tests/e2e/verifier/test_get_credentials_by_proof_id.py, app/tests/e2e/verifier/test_get_records_paginated.py, app/tests/e2e/verifier/test_many_revocations.py, app/tests/e2e/verifier/test_predicate_proofs.py, app/tests/e2e/verifier/test_proof_revoked_credential.py, app/tests/e2e/verifier/test_self_attested.py, app/tests/e2e/verifier/test_verifier.py, app/tests/e2e/verifier/test_verifier_oob.py, trustregistry/tests/e2e/test_actor.py, trustregistry/tests/e2e/test_schema.py
We currently run with `--dist loadfile`, which groups tests by file / module. This means "session" scoped fixtures become module-scoped, which we don't want. Therefore, switch to `--dist loadgroup` (in charts repo) and configure same group for session fixtures
See: https://pytest-xdist.readthedocs.io/en/stable/distribution.html
___
Edit: damn, marks applied to fixtures have no effect. So each test using faber / other session scoped fixtures needs to be marked individually ...
:zap: Looked at test durations to spread tests out across xdist group in a logical way to shorten test runs with fewer xdist workers
(the grouping might seem a bit random, but it was based somewhat on pytest --durations result)
:art: Includes some deduplication, which codacy reported after some files were edited …
=> :test_tube: Configure xdist group for session fixtures

app/tests/e2e/test_definitions.py, app/tests/util/trust_registry.py
These tests create cred defs as governance, meaning governance had to be onboarded as an issuer. This shouldn't be necessary, since we already test same functionality with issuer that's already on trust registry anyway
=> :fire: Remove unnecessary tests

helm/acapy-cloud/conf/dev/multitenant-agent-pg-proxy.yaml, helm/acapy-cloud/conf/dev/multitenant-agent.yaml, helm/acapy-cloud/conf/local/multitenant-agent-pg-proxy.yaml, helm/acapy-cloud/conf/local/multitenant-agent.yaml
:adhesive_bandage:  This is a bandaid for the didexchange scalability issues (see https://github.com/openwallet-foundation/acapy/issues/3492)
=> :wrench: Increase `max_connections` for multitenant agent

helm/acapy-cloud.yaml.gotmpl, helm/acapy-cloud/conf/dev/governance-agent.yaml, helm/acapy-cloud/conf/dev/mediator.yaml, helm/acapy-cloud/conf/dev/multitenant-agent.yaml, helm/acapy-cloud/conf/dev/trust-registry.yaml, helm/acapy-cloud/conf/local/governance-agent.yaml, helm/acapy-cloud/conf/local/mediator.yaml, helm/acapy-cloud/conf/local/multitenant-agent.yaml, helm/acapy-cloud/conf/local/trust-registry.yaml, helm/acapy-cloud/values.yaml, tilt/acapy-cloud/Tiltfile
* Add some Init Containers to make sure Postgres is up
* Governance/Multitenant Agent
* Mediator
* Trust Registry
* Reduces pod restarts due to PG not being up
* Trust Registry doesn't have the Askar bug when using PGPool
* That bug where if the DB doesn't exist it can't connect to a connection pooler
* https://github.com/openwallet-foundation/askar/issues/299
* Trust Registry doesn't create it's own DB, so it can always use PGPool
* NATS does not depend on Istio
* Could _very slightly_ speed up local startup
=> :technologist: Add some Init Containers

.dockerignore, helm/acapy-cloud/conf/dev/endorser.yaml, helm/acapy-cloud/conf/dev/governance-web.yaml, helm/acapy-cloud/conf/dev/multitenant-web.yaml, helm/acapy-cloud/conf/dev/public-web.yaml, helm/acapy-cloud/conf/dev/tenant-web.yaml, helm/acapy-cloud/conf/dev/trust-registry.yaml, helm/acapy-cloud/conf/dev/waypoint.yaml, tilt/acapy-cloud/Tiltfile
* Ignore `tests` in Tilt docker builds
* Resolves very annoying issue where modifying tests causes almost
everything to restart
* Also expand the ignore patterns
* Updating code should only update the affected resource
* e.g: Modifying `endorser/main.py` should not cause `tenant-web` to roll
=> :technologist: Expand Tilt ignore patterns

app/tests/e2e/test_wallet_dids.py, trustregistry/tests/e2e/test_actor.py, trustregistry/tests/e2e/test_schema.py
Wallet DID tests can conflict if they run in parallel, e.g. `test_set_did_endpoint` during `test_list_dids` changes the expected response
=> :white_check_mark: Add xdist group to run tests sequentially

app/poetry.lock, app/pyproject.toml, dockerfiles/agents/Dockerfile, docs/openapi/tenant-admin-openapi.json, docs/openapi/tenant-admin-openapi.yaml, endorser/poetry.lock, endorser/pyproject.toml
Upgrades to latest didx-acapy release: 
https://github.com/didx-xyz/acapy/releases/tag/1.2.1-20250213
plugins:
https://github.com/didx-xyz/acapy-wallet-groups-plugin/releases/tag/1.2.1-20250213
https://github.com/didx-xyz/acapy-plugins/releases/tag/1.2.1-20250213
cloudcontroller:
https://github.com/didx-xyz/aries-cloudcontroller-python/pull/238
=> :arrow_up: Upgrade acapy image to 1.2.1

tilt/acapy-cloud/postgres.yaml
The config was misaligned between postgres and pgpool leading to the following error:
```
2025-02-12 09:39:36.084 GMT [1171] FATAL: remaining connection slots are reserved for roles with the SUPERUSER attribute
``` 
This config aligns for supporting 1000 client connections on postgres with a buffer of 10 reserved for SUPERUSER
=> 🔨  align local dev pgpool & db max connections

app/poetry.lock, app/pyproject.toml, dockerfiles/agents/Dockerfile, endorser/poetry.lock, endorser/pyproject.toml, trustregistry/poetry.lock, waypoint/poetry.lock
Upgrades to:
https://github.com/didx-xyz/acapy/releases/tag/1.2.1-20250228
https://github.com/didx-xyz/acapy-wallet-groups-plugin/pull/71
https://github.com/didx-xyz/acapy-plugins/pull/1078
https://github.com/didx-xyz/aries-cloudcontroller-python/pull/239
=> :arrow_up: Upgrade acapy to 1.2.1-20250228

app/models/verifier.py, app/routes/verifier.py, app/tests/e2e/verifier/test_verifier.py, app/tests/services/verifier/test_verifier.py, docs/openapi/tenant-openapi.json, docs/openapi/tenant-openapi.yaml
Add `credential_id` to results of matching proof as referent is deprecated
=> :bug: Add `credential_id` on matching proofs

helm/acapy-cloud/conf/dev/ledger-browser.yaml, helm/acapy-cloud/conf/local/ledger-browser.yaml, helm/ledger-nodes/values.yaml
Sometimes, after a spot reclaim event, 3/4 of the Ledger Nodes will
successfully recover, however, 1/4 of them will be stuck in a recovering
state.
Added a TCP Port check to the liveness probe to restart the pod if it
gets stuck in a recovering state.
=> :technologist: 🛡️ Improve stability of Ledger Nodes

helm/acapy-cloud/conf/dev/ledger-browser.yaml, helm/acapy-cloud/conf/local/ledger-browser.yaml
* Readiness - should this container receive traffic?
* `/status` -> `/status/text`
* Actually checks if Ledger Browser can talk to Nodes
* Liveness - should this container be restarted?
* `/status`
* Just checks if Ledger Browser Web Service is running
=> :technologist: Fix Ledger Browser Health Probes

helm/acapy-cloud/conf/dev/governance-web.yaml, helm/acapy-cloud/conf/dev/mediator.yaml, helm/acapy-cloud/conf/dev/multitenant-web.yaml, helm/acapy-cloud/conf/dev/public-web.yaml, helm/acapy-cloud/conf/dev/tenant-web.yaml, helm/acapy-cloud/conf/local/governance-web.yaml, helm/acapy-cloud/conf/local/mediator.yaml, helm/acapy-cloud/conf/local/multitenant-web.yaml, helm/acapy-cloud/conf/local/public-web.yaml, helm/acapy-cloud/conf/local/tenant-web.yaml
* For some reason `3020` (DIDComm) is always up even if Agents are down
* Switch to using `3021` (Admin HTTP) instead in Init Containers
* Also use templating where possible to keep things consistent
=> :technologist: :ambulance: Fix Init Containers

app/models/definitions.py, app/routes/definitions.py, app/services/definitions/schema_publisher.py, app/services/definitions/schemas.py, app/tests/routes/definitions/test_get_schema_by_id.py, app/tests/routes/definitions/test_get_schemas.py, app/tests/services/definitions/schema_publisher/test_schema_publisher_anoncreds.py, app/tests/services/definitions/schemas/test_create_schemas.py, app/tests/services/definitions/schemas/test_get_schemas_as_governance.py, app/tests/services/definitions/schemas/test_get_schemas_as_tenant.py, app/tests/services/definitions/schemas/test_get_schemas_by_id.py, app/util/definitions.py, app/util/tenants.py
Add anoncreds schema support
:boom: Removes `schema_id` query parameter from "get_schemas" endpoint (`GET /schemas`) -- since there is already a dedicated endpoint for fetching by schema_id (`GET /schemas/{schema_id}`) -- and the query param was supported in acapy for fetching indy schemas, but no longer for anoncreds schemas, so we adapt and remove it.
=> ✨1 Anoncreds schemas

helm/acapy-test/values.yaml
* Prevent EKS Cluster Autoscaler from evicting tests
=> :construction_worker: Don't evict test pods

.vscode/settings.json, app/models/verifier.py, app/services/verifier/acapy_verifier_v2.py, app/tests/models/test_verifier.py, app/tests/services/onboarding/test_onboarding.py, app/tests/services/verifier/test_acapy_verifier_v2.py, app/tests/services/verifier/test_verifier.py, app/tests/services/verifier/utils.py, app/util/acapy_verifier_utils.py, shared/models/presentation_exchange.py, shared/tests/models/test_presentation_exchange.py
=> ✨ Anoncreds verifier support

app/routes/definitions.py, app/services/definitions/schemas.py, app/tests/conftest.py, app/tests/routes/definitions/test_create_schema.py, app/tests/services/definitions/schemas/test_create_schemas.py, shared/util/mock_agent_controller.py
Temporarily removes the restriction that only governance can create schemas.
This is to accommodate for the fact that we want to test both indy and anoncreds for the time being, and we cannot configure governance to be able to create both. So, we will allow anoncreds issuers to create schemas, until indy support is dropped.
- Removes duplicate auth from schema service
- Updates tests
=> :sparkles: Allow anoncreds issuers to create schemas

app/tests/fixtures/member_wallets.py, app/tests/util/regression_testing.py
Correctly distinguishes Indy Issuer from AnonCreds Issuer in regression fixtures.
=> :test_tube: Configure wallet-type in regression fixtures

app/services/definitions/schema_publisher.py, app/tests/fixtures/definitions.py, app/tests/services/definitions/schema_publisher/test_schema_publisher_anoncreds.py
before publishing it to the trust registry.
Should allow regression mode to pass (previously it tried to fetch schema which was on trust registry, but not on ledger)
=> :sparkles: Wait for anoncreds schema endorsement

app/tests/e2e/conftest.py, app/tests/fixtures/credentials.py, app/tests/routes/definitions/test_create_credential_definition.py
Deduplicates existing indy credential fixtures, to add fixtures for issuing one or many anoncreds, revoking many anoncreds, etc
:boom: Yet again breaks existing regression tests by renaming long-lived credential, in order to distinguish indy from anoncreds
=> :test_tube: Add AnonCreds credential fixtures

.github/actions/deploy-eks/action.yml, helm/acapy-cloud/README.md, helm/acapy-cloud/conf/dev/connect-cloud.yaml, helm/acapy-cloud/conf/local/connect-cloud.yaml, helm/nats/values.yaml, resources/connect-processors/cloud/pipelines/probe-nats-read.yaml, resources/connect-processors/cloud/pipelines/probe-nats-write.yaml, resources/connect-processors/cloud/pipelines/probes.yaml, resources/connect-processors/cloud/resources/probe-resources.yaml, tilt/acapy-cloud/Tiltfile
Adds probe processor to facilitate deep liveness checks:
- probes.yml: provides the http endpoint at /probes/livez
- aggregates the various probes to give a global result: e.g.
- 200 response:
```json
{
"is_live": true,
"nats": {
"read": {
"cached_timestamp": "2025-03-19T12:44:00Z",
"is_cached": true,
"is_live": true
},
"write": {
"cached_timestamp": "2025-03-19T12:44:00Z",
"is_cached": true,
"is_live": true
}
}
}
```
- 503 response:
```json
{
"is_live": false,
"nats": {
"read": {
"cached_timestamp": "2025-03-19T12:44:00Z",
"is_cached": true,
"is_live": false
},
"write": {
"cached_timestamp": "2025-03-19T12:44:00Z",
"is_cached": true,
"is_live": true
}
}
}
```
- probe-nats-write.yml: provides the probe for the nats write endpoint
- uses an in memory cache to facilitate the live probe …
=> 🔨  Add deep connect-cloud liveness probes

.github/workflows/cicd.yml
* When manually triggering a build, only `:branch` is tagged
* Tweak the docker metadata so it does `:branch-sha`
=> :construction_worker: Append SHA to manual builds

.github/actions/test-eks/action.yml
* Don't `--force` when deleting the Pytest Results pod
* Set `terminationGracePeriodSeconds: 5` for aggressive graceful termination
=> :construction_worker: Aggressively gracefully terminate pytest results

.mise/tasks/kind/install/nginx
* Resolves CVE-2025-1098, CVE-2025-1974, CVE-2025-1097, CVE-2025-24514, and CVE-2025-24513
* Only affects publicly exposed local dev
=> :technologist: :arrow_up: Bump Ingress Nginx

helm/acapy-cloud/conf/postgres.yaml
* Closing the connection from PGPool causes Acapy Agents to lose connection to DB
* This causes the liveness probe to fail
* Can cause test failures if the tests start before pod restart
=> 👷 :technologist: Remove PGPool Connection cleanup

app/models/verifier.py, app/tests/e2e/verifier/anoncreds/test_predicate_proofs_anoncreds.py, app/tests/e2e/verifier/anoncreds/test_self_attested_anoncreds.py, app/tests/e2e/verifier/anoncreds/test_verifier.py, app/tests/e2e/verifier/test_proof_revoked_credential.py, app/tests/services/verifier/utils.py
Extended `AnoncredsPresentationRequest` to give default values to `name` and `version` in model. Fix for test that was skipped
=> ✅  Anoncreds test for Self-attested/predicate proofs 

app/tests/e2e/issuer/test_save_exchange_record.py, app/tests/e2e/test_did_exchange.py, app/tests/e2e/test_did_rotate.py, app/tests/e2e/test_jsonld.py, app/tests/e2e/test_oob.py, app/tests/e2e/test_proof_request_models.py, app/tests/e2e/test_wallet_credentials.py, docs/src/examples/7. Verify Credential.md, docs/src/examples/Self-Attested Attributes/1. Self-Attested Attributes.md
Includes:
- test saving exchange records
- testing did exchange and rotate methods
- testing jsonld sign/verifying
- test getting and deleting a wallet credential
=> :test_tube: Migrate e2e tests from indy to anoncreds

.github/workflows/cicd.yml, app/tests/e2e/test_did_rotate.py, pyproject.toml
Only print the 25 slowest tests, and skip coverage results in terminal output for 100% covered modules
Ultimately reduces noise in output of test jobs
=> :construction_worker: Tweak pytest output

resources/connect-processors/cloud/pipelines/cloud-events.yaml
`created_at` and `updated_at` is null on local (not sure about the rest)
- Use `this` to get events  `created_at` and `updated_at` time.
- Use `ts_unix_micro` (Looks like time stamps have 6 digits after decimal point )
=> 🐛 Fix connect processor

.github/workflows/cicd.yml, .github/workflows/deploy-test-eks.yml, .github/workflows/docker-build.yml, .github/workflows/format.yml, .github/workflows/local-tests.yml, .github/workflows/notify.yml, .github/workflows/unit.yml
* Renamed jobs in `cicd.yml` for clarity: "Format Check" → "Lint",
"Unit Tests" → "Tests", etc.
* Added proper workflow names to files that were missing them
* Reorganized job dependencies to match the new naming scheme
* Consolidated concurrency settings for Docker builds
* Improved consistency across all workflow files
=> :memo: Improve workflow naming

.github/workflows/README.md, .github/workflows/cicd.yml, .github/workflows/update-openapi.yml, dockerfiles/app/Dockerfile, dockerfiles/endorser/Dockerfile, dockerfiles/trustregistry/Dockerfile, dockerfiles/waypoint/Dockerfile, scripts/download_openapi_specs.sh
Add GitHub workflow for automatically managing OpenAPI specifications:
- Create new OpenAPI workflow job in the CI/CD pipeline
- Add tooling to compare and diff API specs
- Automatically comment on PRs with API changes
- Create PRs for syncing OpenAPI specs with code changes
- Set `PYTHONPATH` in all service Dockerfiles for proper imports
=> :construction_worker: :memo: Add OpenAPI spec automation workflow

.github/workflows/cicd.yml, .github/workflows/update-openapi.yml
Replace empty string with 0 for default PR number value to ensure
consistent type handling in conditional statements. This addresses
issues with string vs numeric comparisons in workflow conditions.
Improve checkout reference to dynamically use PR head sha when in PR
context, falling back to repository default branch otherwise. This
ensures more reliable behavior across different workflow trigger
contexts.
=> 👷 Fix PR number handling in OpenAPI GitHub workflow

app/models/tenants.py, app/routes/admin/tenants.py, app/services/onboarding/tenants.py, app/tests/routes/admin_tenants/test_create_tenant.py, app/util/tenants.py, dockerfiles/agents/Dockerfile, docs/openapi/tenant-openapi.json, docs/openapi/tenant-openapi.yaml, poetry.lock, pyproject.toml
I'm busy regenerating the cloudcontroller with Cheqd endpoints, and noticed the group-id plugin models should be updated
plugin changes: https://github.com/didx-xyz/acapy-wallet-groups-plugin/pull/80
cloudcontroller changes: https://github.com/didx-xyz/aries-cloudcontroller-python/pull/246
___
Includes model renames / refactoring for Create/Update tenant requests. (Note: does not impact API spec, because these cloudcontroller models are used internally, and not in client-side request bodies -- the openapi changes are for `cheqd` being added to supported DID methods, from cloudcontroller update)
=> :arrow_up: Upgrade wallet-group-id plugin and cloudcontroller

.github/workflows/update-openapi.yml
Use `env` to get around JS and Github Actions variable interpolation shenanigans
=> 👷 🐛 Fix OpenAPI diff interpolation

.github/workflows/format.yml, .github/workflows/sonarcloud.yml, .mise.toml, .pylintrc, README.md, dockerfiles/app/Dockerfile, dockerfiles/endorser/Dockerfile, dockerfiles/tests/Dockerfile, dockerfiles/trustregistry/Dockerfile, dockerfiles/waypoint/Dockerfile, poetry.lock, pyproject.toml
There seems to be an issue with Uvicorn/FastAPI under load getting a SIGSEGV (segmentation fault) without any logs.
It's very inconsistent and happens after a while of throwing load at it (via k6)
@wdbasson
This is to test if reverting the Python 3.13 upgrade resolves the issue.
=> :rewind: Revert Python 3.13 upgrade

.github/workflows/update-openapi.yml
Using the Markdown diff output resulted in a significant number of gremlins with formatting Markdown within Markdown.
Started trying to do a lot of escapes and formatting, the script very quickly exploded in complexity.
---
:recycle: Refactor OpenAPI update workflow
Simplify OpenAPI spec downloading by fetching directly to final locations
without intermediate directories. Replace `oasdiff-action` with native
`git diff` for change detection to reduce external dependencies.
Streamline PR comment creation with improved change detection logic and
file-based diff approach. This change reduces redundant code paths and
improves overall workflow efficiency.
=> :construction_worker: :bug: Fix formatting OpenAPI diff

app/models/issuer.py, app/routes/issuer.py, app/services/issuer/acapy_issuer.py, app/services/issuer/acapy_issuer_v2.py, app/tests/models/test_issuer.py, app/tests/routes/issuer/test_create_offer.py, app/tests/routes/issuer/test_request_credential.py, app/tests/routes/issuer/test_send_credential.py, app/tests/services/issuer/test_acapy_issuer_v2.py, app/tests/services/issuer/test_issuer.py, app/tests/test_util_wallet_type_checks.py, app/util/valid_issuer.py, app/util/wallet_type_checks.py, dockerfiles/agents/Dockerfile, docs/openapi/tenant-admin-openapi.json, docs/openapi/tenant-admin-openapi.yaml, docs/openapi/tenant-openapi.json, docs/openapi/tenant-openapi.yaml, poetry.lock, pyproject.toml, shared/models/credential_exchange.py, shared/tests/models/test_credential_exchange.py
Also removes "type" option from credentials -- just pass `anoncreds_credential_detail`, or `ld_credential_detail`.
(Relates to #1501)
=> :boom: Drop Indy credential type

.github/workflows/cicd.yml, .github/workflows/update-openapi.yml
Streamline workflow by removing redundant PR number input parameter
and using GitHub context variables directly. Add condition to skip 
workflow on tag-based releases to prevent unnecessary runs.
Improve PR creation process with file-based body content for better 
multi-line handling. Use workflow warning command for better 
visibility of OpenAPI spec changes in logs.
Simplify checkout configuration by using appropriate tokens based 
on event context and removing unnecessary reference specifications.
=> :construction_worker: Refine OpenAPI workflow configuration

.github/workflows/cicd.yml
Fixes the workflow issues in #1541 and #1543
=> :construction_worker: Disable OpenAPI updates for Dependabot PRs

.github/workflows/cicd.yml, .github/workflows/deploy-test-eks.yml, .github/workflows/docker-build.yml, scripts/k6/.mise.toml, scripts/k6/Dockerfile, scripts/k6/env.sh, scripts/k6/libs/functions.js, scripts/k6/libs/schemaUtils.js, scripts/k6/run_tests.sh, scripts/k6/scenarios/create-creddef.js, scripts/k6/scenarios/create-invitations.js, scripts/k6/scenarios/create-issuers.js, scripts/k6/scenarios/delete-holders.js
* Upgrade k6 from v0.56.0 to v1.0.0
* Update xk6 CLI from v0.13.4 to v0.19.3
* Update xk6 extensions to latest versions
* Switch Golang base image to Alpine for reduced size
* Update Node.js from 22 to 24
* Improve Docker configuration with proper permissions and staging
Reintroduce K6 testing as part of the CI/CD pipeline.
The implementation configures Docker to run k6 tests against the deployed
application.
=> :rocket: :construction_worker: Re-implement k6 tests in CI/CD pipeline

app/tests/fixtures/member_connections.py, app/tests/util/connections.py
Replaces test fixtures that connect to issuers using their public DID to instead connect using their trust registry OOB invitation
Serves as a stepping stone to supporting did:cheqd, since it's currently not possible to connect using a cheqd public DID
=> :recycle: :test_tube: Refactor connection fixtures

poetry.lock, pyproject.toml
With `orjson` and `uuid-utils` extras (from https://github.com/nats-io/nats.py/pull/674)
___
Includes fix for RuntimeWarning:
- https://github.com/nats-io/nats.py/issues/646
=> :arrow_up: Use nats-py with orjson

.github/workflows/cicd.yml, .github/workflows/local-tests.yml, tilt/acapy-cloud/Tiltfile
Configure the GitHub Actions workflow to pass the Cheqd testnet mnemonic
secret to the `driver-did-cheqd` component. This allows the driver to
interact with the Cheqd testnet blockchain during CI/CD runs and local
tests.
* The mnemonic is used as a fee-payer account for testnet transactions
* Added as a required secret to both `cicd.yml` and `local-tests.yml` workflows
* Passed as `FEE_PAYER_TESTNET_MNEMONIC` environment variable to Tilt
=> :construction_worker: Add Cheqd testnet mnemonic to CI/CD

dockerfiles/app/Dockerfile, dockerfiles/tails/Dockerfile, dockerfiles/trustregistry/Dockerfile, dockerfiles/waypoint/Dockerfile, helm/acapy-cloud/conf/local/governance-web.yaml, helm/acapy-cloud/conf/local/multitenant-web.yaml, helm/acapy-cloud/conf/local/public-web.yaml, helm/acapy-cloud/conf/local/tails-server.yaml, helm/acapy-cloud/conf/local/tenant-web.yaml, helm/acapy-cloud/conf/local/trust-registry.yaml, helm/acapy-cloud/conf/local/waypoint.yaml, tilt/acapy-cloud/Tiltfile
* Remove `--chown` flags from `COPY` commands in Dockerfiles
* Set `runAsUser: 0` and `runAsNonRoot: false` in local Helm configs
Tilt requires root privileges to modify files during live reload.
This configuration is isolated to local development environment
and does not affect production security posture.
* Tails depends on MinIO
* Resources depend on base values file
---
> [!NOTE]
> Turns out the below is a MacOS issue.
Fixes Tilt Live Update.
Modified files get copied into running containers and Uvicorn successfully
picks up the change and restarts, but Tilt fails with a `chown` which results
in an error.
I've opened a [feature request](https://github.com/tilt-dev/tilt/issues/6562) to add support for `--no-preserve` in live
updates to get around the `chown` issue.
=> :bug: :technologist: Fix Tilt Live Update

.github/workflows/deploy-test-eks.yml, .github/workflows/docker-build.yml, .github/workflows/format.yml, .github/workflows/mdbook-deploy.yml, helm/acapy-cloud/conf/dev/driver-did-cheqd.yaml, helm/acapy-cloud/conf/local/driver-did-cheqd.yaml, helm/acapy-cloud/templates/istio-peerauth.yaml, helm/acapy-cloud/templates/istio-sidecar.yaml, helm/acapy-cloud/templates/istio-virtualservice.yaml, tilt/acapy-cloud/Tiltfile
Reorganize GitHub workflow input parameters for better logical 
grouping and consistency. Update several configuration files to 
use current API versions and improve naming conventions.
Changes made:
* Reorder workflow inputs in `deploy-test-eks.yml` to be
alphabetical
* Update workflow names to use consistent format with forward 
slashes (`Deploy / Test EKS`, `Lint / Format`, `MDBook Deploy`)
* Change Docker build cache mode from `max` to `min` for 
faster caching
* Update Istio resource API versions from `v1beta1` to `v1`
* Update cheqd did-registrar image tag from `develop` to 
`2.6.0-1-g6979b43` and remove digest
* Simplify mnemonic comments by removing "Testnet" references
* Improve comment clarity in `.mise.toml` overwrite step
* Clean up spacing in mdbook workflow permissions
=> :recycle: Reorganize workflow inputs and update configs

app/tests/e2e/issuer/test_concurrent_issuance_revocation.py, dockerfiles/agents/Dockerfile, helm/acapy-cloud.yaml.gotmpl, helm/acapy-cloud/conf/dev/governance-agent.yaml, helm/acapy-cloud/conf/dev/mediator.yaml, helm/acapy-cloud/conf/dev/multitenant-agent.yaml, helm/acapy-cloud/conf/dev/public-web.yaml, helm/acapy-cloud/conf/local/governance-agent.yaml, helm/acapy-cloud/conf/local/mediator.yaml, helm/acapy-cloud/conf/local/multitenant-agent.yaml, helm/acapy-cloud/conf/local/public-web.yaml, helm/acapy-cloud/conf/valkey.yaml, helm/acapy-cloud/templates/deployment.yaml, helm/nats/Chart.lock, tilt/acapy-cloud/Tiltfile, tilt/metrics/Tiltfile
* Add [Valkey](https://valkey.io) Helm release with replication architecture
* Configure Valkey with authentication disabled and 1Gi storage
* Update PostgreSQL HA chart from `16.0.10` to `16.0.11`
* Update MinIO chart from `17.0.2` to `17.0.3`
* Update metrics-server chart from `7.4.5` to `7.4.6`
* Remove redundant init containers waiting for agent services
* Replace hardcoded `governance-agent` checks with trust registry URL
* Add Valkey as dependency for `governance` and `multitenant` agents
This change introduces Valkey as a Redis-compatible in-memory data
store for distributed locking mechanisms. The configuration uses
standalone architecture without authentication for development
environments.
The init container cleanup removes dependencies on specific agent
services, making the …
=> :sparkles: Add Valkey for distributed locking

app/main.py
Resolve bug where Scalar UI defaulted to `/` root path causing
API endpoints to return 404 errors. Previously, users had to
manually refresh the page to trigger FastAPI to update
`app.servers` with the correct root path.
* Use `ROOT_PATH` directly in servers configuration
* Eliminate need for manual page refresh to fix API paths
* Ensure Scalar UI uses correct root path from initial load
=> :bug: Fix Scalar missing root path on initial load

.github/dependabot.yml
Attempt to:
- keep 1 individual PR for root dependencies
- group dockerfile pip dependencies into 1 PR
=> :construction_worker: Dependabot: Group docker pip dependencies

app/tests/e2e/issuer/test_anoncreds_credentials.py, app/tests/e2e/test_messaging.py, dockerfiles/agents/poetry.lock, dockerfiles/agents/pyproject.toml, resources/connect-processors/cloud/pipelines/cloud-events.yaml
Rework some test to remove error logs related to agent trying to send messages/credentials to deleted wallets
example of error logs:
`Exceeded retry limit for verkey: 2yQj8ebpGap7S9SXvyXNZV3YkfENcxrAFSUBMtEWnzrq`
`parsed_msg does not contain @type: {'protected':...`
`Message parsing failed: Message does not contain '@type' parameter, sending problem report`
=> ✅ Reduce error logs from tests

helm/cheqd/templates/service.yaml, helm/cheqd/templates/statefulset.yaml, helm/cheqd/values.yaml
* Add Headless Service for internal peer discovery (High Availability)
* Add environment variables
* Update Testnet Snapshot date/checksum
* Add the `CHEQD_NODED_P2P_PERSISTENT_PEERS` environment variable for
configuring peers within the K8s cluster (High Availability)
=> :wrench: :technologist: Cheqd chart updates

scripts/k6/libs/k6Functions.js, scripts/k6/scenarios/bootstrap-issuer.js, scripts/k6/scenarios/create-creddef.js, scripts/k6/scenarios/create-credentials.js, scripts/k6/scenarios/create-holders.js, scripts/k6/scenarios/create-invitations.js, scripts/k6/scenarios/create-issuers.js, scripts/k6/scenarios/create-proof.js, scripts/k6/scenarios/create-schemas.js, scripts/k6/scenarios/delete-holders.js, scripts/k6/scenarios/delete-issuers.js, scripts/k6/scenarios/publish-revoke.js, scripts/k6/scenarios/revoke-credentials.js
- Support k6 `setup()` and `teardown()` phases in custom logging function
- Retry publishing revocation
- Use JSON lines file extension: `.jsonl`
- Programatically set k6 `test_phase` tag when creating proofs
=> ✅ K6 improvements to revocation

helm/cheqd/templates/statefulset.yaml, helm/cheqd/values.yaml
* Add conditional lifecycle configuration block to StatefulSet
template that references `.Values.lifecycle`
* Include preStop hook with 5-second sleep delay in default
values for graceful pod termination
* Add commented examples for `GOMEMLIMIT` and `GOMAXPROCS`
environment variables with resource field references
* Update commented memory limit example from 4Gi to 2.75Gi
This enables users to configure custom lifecycle hooks for the
cheqd container, improving graceful shutdown behavior and
providing better resource management options.
=> :wrench: Add lifecycle hook support to Cheqd Helm chart

helm/acapy-cloud/conf/dev/governance-agent.yaml, helm/acapy-cloud/conf/dev/governance-web.yaml, helm/acapy-cloud/conf/local/governance-agent.yaml, helm/acapy-cloud/conf/local/governance-web.yaml, helm/acapy-cloud/templates/job.yaml, helm/acapy-cloud/values.yaml, helm/cheqd/values.yaml
* Add `ACAPY_WALLET_ALLOW_INSECURE_SEED` environment variable to
governance agent configurations (dev and local) to enable DID
bootstrapping with a predefined seed
* Implement post-install/post-upgrade Helm hook job that automatically
creates a governance DID if one doesn't already exist, using the
cheqd method and a wallet seed
* Add job template support to acapy-cloud Helm chart with configurable
jobs section in values.yaml to enable running arbitrary jobs as part
of chart lifecycle
* Remove unused podLabels and podAnnotations from cheqd snapshot
configuration
This change eliminates the need for manual DID creation after
deployment by automating the governance DID bootstrap process,
ensuring the governance agent is ready to use immediately after
installation.
=> :sparkles: Add Governance DID bootstrap job

helm/acapy-cloud.yaml.gotmpl, helm/nats/Chart.lock, tilt/acapy-cloud/Tiltfile
* Update valkey from 3.0.15 to 3.0.16
* Update postgresql-ha from 16.0.14 to 16.0.15
* Update minio from 17.0.6 to 17.0.9
* Update nats from 9.0.20 to 9.0.21
* Update corresponding version variables in Tiltfile
These updates bring all Bitnami chart dependencies to their
latest stable releases for improved security and bug fixes.
=> :arrow_up: Upgrade Bitnami chart dependencies

.gitignore, helm/acapy-cloud.yaml.gotmpl, helm/cheqd/conf/localnet/values.yaml, helm/cheqd/templates/statefulset.yaml, helm/cheqd/values.yaml, tilt/acapy-cloud/Tiltfile
This PR upgrades the cheqd-node dependency from v3.1.9 to v4.1.0 to
maintain parity with the cheqd testnet, which is upgrading to v4.1.0
on July 2nd, 2025.
* Upgrade cheqd-node version to v4.1.0 in Helm values
* Remove local build and checkout logic for cheqd-node repository  
* Fix Tilt UI links to use correct `cloudapi` domain structure
* Rename configuration key from `cheqd` to `cheqdLocalNet` for clarity
* Clean up `.gitignore` to remove `.cheqd-node` directory reference
* Remove `cheqd_noded_version` variable from Tiltfile
**Primary motivation**: The cheqd testnet is upgrading from v3.1.9 to 
v4.1.0 on July 2nd, 2025. To ensure our local development environment 
remains compatible and behaves consistently with the testnet, we need 
to upgrade our localnet deployment to match this …
=> :arrow_up: Cheqd Localnet `4.1.0`

helm/cheqd/templates/statefulset.yaml, helm/cheqd/values.yaml
Add optional data directory reset before snapshot restoration.
This allows operators to force a clean snapshot download by
setting `snapshot.reset: true` in values.yaml.
Changes:
* Add conditional data directory removal in statefulset init
* Add `reset: false` configuration option to values.yaml
The reset functionality removes `/cheqd/data` when enabled,
ensuring a fresh snapshot download instead of resuming from
existing blockchain state.
=> :sparkles: Add snapshot reset functionality to Cheqd Helm

.mise.toml, Tiltfile, tilt/README.md, tilt/acapy-cloud/Tiltfile
Adds the ability to choose between self-hosted cheqd node deployment or using the Cheqd Testnet
- New flag: --no-cheqd to disable self-hosted cheqd deployment
- Dynamic configuration:
- did-resolver uses grpc.cheqd.network:443,true,5s when centralized
- driver-did-cheqd uses https://rpc.cheqd.network and empty mnemonic when centralized
- Removes cheqd service dependency when not self-hosted
- Improved mise integration: Enable passing Tiltfile arguments through mise tasks
mise run tilt:up
mise run tilt:up -- --no-cheqd
mise run tilt:up -- --no-build --no-cheqd
=> 🧑‍💻 Tilt no cheqd

app/models/tenants.py, docs/openapi/tenant-admin-openapi.json, docs/openapi/tenant-admin-openapi.yaml
This change removes the existing example that was used in the `extra_settings` field for the CreateTenant endpoint.
The example was there in order to illustrate an advanced-user setting (changing `ACAPY_AUTO_ACCEPT_INVITES` to False), but this has the drawback of that example being auto-filled, in the Scalar UI, in the sample create tenant request payload. Meaning, if someone naively creates a tenant with the example request, then the auto-accept flags would be disabled, breaking the recommended flows. Rather than changing the example to set the auto-accept value to True, it's better to just remove it, and avoid all confusion, since True is already the default behaviour.
The extra_settings field description is also updated to indicate that it is only relevant for advanced use cases.
=> :art: Remove create-tenant "extra settings" example

Tiltfile
Add `--merge` flag to `git submodule update` command to prevent 
resetting uncommitted changes in submodules during Tilt startup.
The previous command would discard any uncommitted changes in 
submodule directories when initializing/updating. Adding `--merge` 
preserves local modifications while still ensuring submodules are 
properly initialized for development workflows.
=> :adhesive_bandage: Preserve uncommitted submodule changes in Tilt

Tiltfile
Change submodule handling to only initialize submodules that are 
not already initialized, avoiding any potential disruption to 
existing submodule state.
* Update message to reflect initialization-only behavior
* Use `git submodule status | awk '/^-/ {print $2}'` to extract 
paths of uninitialized submodules (those with `-` prefix)
* Use `xargs -r git submodule update --init` to initialize only 
the specific submodules that need it
* The `-r` flag prevents `xargs` from running when no 
uninitialized submodules exist
Git submodule status prefixes:
* ` ` (space) - initialized submodule at correct commit
* `-` - uninitialized submodule 
* `+` - initialized submodule with different commit than expected
This approach is more precise and efficient, only initializing 
the specific submodules …
=> :adhesive_bandage: Only initialize uninitialized submodules in Tilt

app/exceptions/handle_acapy_call.py, shared/util/rich_async_client.py
For handling acapy calls:
- will now log error message, instead of exception stack trace, for a `ClientConnectionResetError`
For RichAsyncClient (internally used for app requests to trust registry):
- handles `RemoteProtocolError` with an error log (previously would print stack trace, without loguru stack-trace wrapping)
- any other exception will print the stack-trace, with loguru wrapping
- above cases are not retried (only HTTPStatusError and ConnectTimeout should be retried by RichAsyncClient)
=> :mute: Improve exception logging

helm/cheqd/templates/statefulset.yaml
* Remove redundant conditional checks for existing snapshot files
and partial downloads in the snapshot download logic
* Update genesis.json URL to use versioned branch
(`v{{ .Values.image.tag }}`) instead of `main` branch
* Streamline aria2c download process by removing file existence
checks that were causing unnecessary complexity
The snapshot download now consistently downloads fresh snapshots
without checking for existing files, making the process more
predictable and easier to debug. The genesis URL fix ensures
compatibility with specific node versions rather than always
pulling from the main branch.
=> :recycle: Simplify snapshot download and pin genesis URL

.github/workflows/codacy.yml
Disable SARIF upload due to pending fixes in related dependencies and
to avoid issues with code scanning.
The upload will be re-enabled once the upstream issues are resolved.
---
https://github.blog/changelog/2025-07-21-code-scanning-will-stop-combining-multiple-sarif-runs-uploaded-in-the-same-sarif-file
https://github.com/codacy/codacy-analysis-cli-action/issues/142
=> :green_heart: Temporarily disable Codacy SARIF upload

.github/workflows/cicd.yml, .github/workflows/deploy-test-eks.yml, helm/acapy-cloud.yaml.gotmpl, helm/nats/Chart.lock, tilt/acapy-cloud/Tiltfile, tilt/metrics/Tiltfile
This commit updates multiple dependencies and tools to their latest
versions to ensure security patches and improved functionality:
* Update Helmfile from v1.1.3 to v1.1.4 in CI workflows
* Update Mise from 2025.8.4 to 2025.8.7 in CI workflows
* Update `didx-xyz/workflows/connect-eks` action to latest commit
* Upgrade Helm chart versions:
* Valkey: 3.0.22 → 3.0.28
* PostgreSQL HA: 16.1.0 → 16.1.2
* pgAdmin4: 1.47.0 → 1.48.0
* MinIO: 17.0.16 → 17.0.19
* NATS: 9.0.24 → 9.0.25
* Metrics Server: 7.4.10 -> 7.4.11
* Update corresponding version references in Tiltfile
* Regenerate Chart.lock with updated dependencies
These updates include bug fixes, security improvements, and feature
enhancements from upstream projects.
=> :arrow_up: Update dependencies and tools

tilt/metrics/Tiltfile
Switch from Bitnami metrics-server chart to the official
Kubernetes SIG chart in Tilt development environment to avoid
disruption from upcoming Bitnami catalog changes.
Bitnami will deprecate their public catalog on August 28th,
2025, moving images to a legacy repository with no updates.
This migration ensures continued support and security updates.
Changes:
* Add explicit helm repository resource for metrics-server
* Update chart reference from Bitnami OCI registry to official
Kubernetes SIG Helm repository
* Change `extraArgs` configuration to `args` format for
official chart compatibility
* Remove `--metric-resolution=15s` argument (not needed)
* Keep `--kubelet-insecure-tls` for development environment
* Add resource dependency on helm repository
---
For more info: …
=> :truck: Migrate to official metrics-server chart

.github/workflows/cicd.yml, .github/workflows/codacy.yml, .github/workflows/deploy-test-eks.yml, .github/workflows/docker-build.yml, .github/workflows/format.yml, .github/workflows/local-tests.yml, .github/workflows/mdbook-deploy.yml, .github/workflows/notify.yml, .github/workflows/scorecards.yml, .github/workflows/sonarcloud.yml, .github/workflows/unit.yml, .github/workflows/update-openapi.yml, .mise.toml, .mise/tasks/kind/create, .mise/tasks/kind/destroy, .mise/tasks/kind/install/docker-cache, .mise/tasks/kind/install/docker-registry, .mise/tasks/kind/install/istio, .mise/tasks/kind/install/nginx, scripts/k6/Dockerfile
This PR updates various dependencies across the project and migrates mise task comments to the new `#MISE` format in preparation for the deprecation of `# mise` syntax.
- **Helm**: v3.18.4 → v3.18.5
- **Helmfile**: v1.1.4 → v1.1.5  
- **Mise**: 2025.8.7 → 2025.8.13
- **istioctl**: 1.26 → 1.27
- **Golang**: 1.24-alpine → 1.25-alpine
- **github/codeql-action**: 3.29.8 → 3.29.10
- **helmfile/helmfile-action**: 2.0.4 → 2.0.5
- **actions/upload-pages-artifact**: 3.0.1 → 4.0.0 (major version)
- **actions/checkout** 4.2.2 -> 5.0.0 (major version)
- **jdx/mise-action** 2.4.4 -> 3.0.2 (major version)
- **MishaKav/pytest-coverage-comment**: 1.1.54 → 1.1.56
- **actions/create-github-app-token**: 2.1.0 → 2.1.1
- Migrated all `# mise` task comments to `#MISE` format across kind-related tasks
- The `# …
=> :arrow_up: Update dependencies and migrate to `#MISE` syntax

helm/acapy-cloud/conf/dev/connect-cloud.yaml, helm/acapy-cloud/conf/dev/governance-agent.yaml, helm/acapy-cloud/conf/dev/multitenant-agent.yaml, helm/acapy-cloud/conf/dev/waypoint.yaml, helm/acapy-cloud/conf/local/connect-cloud.yaml, helm/acapy-cloud/conf/local/governance-agent.yaml, helm/acapy-cloud/conf/local/multitenant-agent.yaml, helm/acapy-cloud/conf/local/waypoint.yaml, helm/acapy-cloud/conf/minio.yaml, helm/acapy-cloud/conf/postgres.yaml, helm/acapy-cloud/conf/valkey.yaml, helm/cheqd/templates/statefulset.yaml, helm/nats/templates/job.yaml, helm/nats/values.yaml
Switch Bitnami container images from `bitnami/` to
`docker.io/bitnamilegacy/` to maintain functionality during
the Bitnami catalog transition period.
This is a temporary workaround until proper migration to
official upstream charts is completed. The legacy repository
contains archived images with no further updates and should
only be used for migration purposes.
Changes:
* Update image repositories across all Helm configurations:
- NATS CLI, MinIO, PostgreSQL, Valkey, kubectl images
* Add `global.security.allowInsecureImages: true` to override
repository validation in Bitnami charts
* Update both local and dev environment configurations
* Maintain existing functionality while planning permanent
migration to upstream charts
Images migrated: natscli, minio, minio-client, …
=> :truck: Migrate to Bitnami legacy repository temporarily

helm/acapy-cloud.yaml.gotmpl, helm/acapy-cloud/conf/dev/connect-cloud.yaml, helm/acapy-cloud/conf/dev/governance-agent.yaml, helm/acapy-cloud/conf/dev/multitenant-agent.yaml, helm/acapy-cloud/conf/dev/waypoint.yaml, helm/acapy-cloud/conf/local/connect-cloud.yaml, helm/acapy-cloud/conf/local/governance-agent.yaml, helm/acapy-cloud/conf/local/multitenant-agent.yaml, helm/acapy-cloud/conf/local/waypoint.yaml, helm/acapy-cloud/conf/minio.yaml, helm/acapy-cloud/conf/postgres.yaml, helm/acapy-cloud/conf/valkey.yaml, helm/cheqd/Chart.yaml, helm/cheqd/templates/statefulset.yaml, helm/nats/Chart.lock, helm/nats/Chart.yaml, helm/nats/templates/job.yaml, helm/nats/values.yaml, tilt/acapy-cloud/Tiltfile
Replace official Bitnami chart and image repositories with custom
`ghcr.io/didx-xyz/bitnami-oss` registry to address deprecation and
availability issues with upstream repositories.
Changes include:
* Update Helm chart sources from `registry-1.docker.io/bitnamicharts`
to `ghcr.io/didx-xyz/bitnami-oss-charts`
* Migrate container images from `docker.io/bitnamilegacy` to
`ghcr.io/didx-xyz/bitnami-oss`
* Add `imageRegistry: ghcr.io` to global chart configurations
* Update repository references for PostgreSQL, Valkey, MinIO, NATS,
and related utility images
This migration ensures continued availability and support for Bitnami-
based services while maintaining compatibility with existing
configurations.
References: bitnami/charts#35164, bitnami/containers#83267
=> :truck: Migrate Bitnami charts to custom registry

.github/workflows/cicd.yml, .mise/tasks/kind/install/nginx, helm/acapy-cloud.yaml.gotmpl, helm/nats/Chart.lock, tilt/acapy-cloud/Tiltfile
Upgrade local infrastructure to their latest versions:
* Helm upgraded from v3.18.5 to v3.18.6
* Helmfile upgraded from v1.1.5 to v1.1.6
* Ingress Nginx upgraded from 4.13.0 to 4.13.2
* Valkey upgraded from 3.0.31 to 4.0.0
* PostgreSQL HA upgraded from 16.3.1 to 16.3.4
* MinIO upgraded from 17.0.21 to 17.0.22
* NATS upgraded from 9.0.28 to 9.0.29
* Bitnami common chart upgraded from 2.31.4 to 2.31.5
=> :arrow_up: Upgrade Helm, Helmfile, and local infra
